// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGitDotNet;

/// <summary>Lazily iterates over <see cref="Commit"/> objects returned by go-git. Must be disposed after use.</summary>
public sealed class CommitIterator : IEnumerable<Commit>, IDisposable
{
    private long _handle;
    private bool _disposed;

    internal CommitIterator(long handle) => _handle = handle;

    public IEnumerator<Commit> GetEnumerator()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        while (true)
        {
            var err = NativeMethods.GitCommitIterNext(
                _handle,
                out var commitHandle, out var eof);
            NativeMethods.ThrowIfError(err);

            if (eof != 0) yield break;

            yield return new Commit(commitHandle);
        }
    }

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitCommitIterFree(_handle);
        _handle = 0;
    }
}
