// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGitDotNet;

/// <summary>Lazily iterates over <see cref="File"/> objects returned by go-git. Must be disposed after use.</summary>
public sealed class FileIterator : IEnumerable<File>, IDisposable
{
    private long _handle;
    private bool _disposed;

    internal FileIterator(long handle) => _handle = handle;

    public IEnumerator<File> GetEnumerator()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        while (true)
        {
            var err = NativeMethods.GitFileIterNext(
                _handle,
                out var fileHandle, out var eof);
            NativeMethods.ThrowIfError(err);

            if (eof != 0) yield break;

            yield return new File(fileHandle);
        }
    }

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitFileIterFree(_handle);
        _handle = 0;
    }
}
