// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Runtime.InteropServices;

namespace GoGit.Interop;

public sealed class Auth : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Auth(long handle) => _handle = handle;
    internal long Handle => _handle;

    public static Auth BasicHTTP(string username, string password)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitAuthNewBasicHTTP(username, password, out var handle));
        return new Auth(handle);
    }

    public static Auth TokenHTTP(string token)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitAuthNewTokenHTTP(token, out var handle));
        return new Auth(handle);
    }

    public static Auth SSHKeyFromFile(string user, string pemFile, string password = "")
    {
        NativeMethods.ThrowIfError(NativeMethods.GitAuthNewSSHKeyFromFile(user, pemFile, password, out var handle));
        return new Auth(handle);
    }

    public static Auth SSHKey(string user, string pem, string password = "")
    {
        NativeMethods.ThrowIfError(NativeMethods.GitAuthNewSSHKey(user, pem, password, out var handle));
        return new Auth(handle);
    }

    public static Auth SSHAgent(string user)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitAuthNewSSHAgent(user, out var handle));
        return new Auth(handle);
    }

    public static Auth SSHPassword(string user, string password)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitAuthNewSSHPassword(user, password, out var handle));
        return new Auth(handle);
    }

    public Auth SetInsecureIgnoreHostKey()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitAuthSetInsecureIgnoreHostKey(_handle));
        return this;
    }

    public Auth SetKnownHostsFiles(params string[] paths)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        var json = System.Text.Json.JsonSerializer.Serialize(paths);
        NativeMethods.ThrowIfError(NativeMethods.GitAuthSetKnownHostsFiles(_handle, json));
        return this;
    }

    public delegate string? GitHostKeyCallback(string hostname, string remoteAddr, string keyType, string keyBase64);

    private GCHandle? _hostKeyCallbackHandle;

    public Auth SetHostKeyCallback(GitHostKeyCallback callback)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);

        NativeHostKeyCallback native = (hostname, remoteAddr, keyType, keyBase64, _) =>
        {
            var result = callback(
                Marshal.PtrToStringUTF8(hostname)!,
                Marshal.PtrToStringUTF8(remoteAddr)!,
                Marshal.PtrToStringUTF8(keyType)!,
                Marshal.PtrToStringUTF8(keyBase64)!);
            return result != null ? Marshal.StringToCoTaskMemUTF8(result) : IntPtr.Zero;
        };

        _hostKeyCallbackHandle?.Free();
        _hostKeyCallbackHandle = GCHandle.Alloc(native);
        var fnPtr = Marshal.GetFunctionPointerForDelegate(native);
        NativeMethods.ThrowIfError(NativeMethods.GitAuthSetHostKeyCallback(_handle, fnPtr, IntPtr.Zero));
        return this;
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate IntPtr NativeHostKeyCallback(IntPtr hostname, IntPtr remoteAddr, IntPtr keyType, IntPtr keyBase64, IntPtr userData);

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        _hostKeyCallbackHandle?.Free();
        _hostKeyCallbackHandle = null;
        NativeMethods.GitAuthFree(_handle);
        _handle = 0;
    }
}
