// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json;

namespace GoGit.Interop;

/// <summary>A file inside a git tree. Provides access to the file name, hash, and contents. Wraps <c>*object.File</c> from go-git.</summary>
public sealed class File : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal File(long handle) => _handle = handle;
    internal long Handle => _handle;

    public string Contents()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitFileContents(_handle, out var s));
        return NativeMethods.ConsumeGoString(s)!;
    }

    public bool IsBinary()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitFileIsBinary(_handle, out var val));
        return val != 0;
    }

    public string[] Lines()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitFileLines(_handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<string[]>(json) ?? [];
    }

    /// <summary>The file path relative to the repository root.</summary>
    public string Name
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitFileGetName(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public uint Mode
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitFileGetMode(_handle, out var val));
            return val;
        }
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitFileFree(_handle);
        _handle = 0;
    }
}
