// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class GoGitException : Exception
{
    public GoGitException(string message) : base(message) { }
}
