// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json;

namespace GoGit.Interop;

public sealed class Repository : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Repository(long handle) => _handle = handle;

    public static Repository Init(string path, bool isBare = false)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitPlainInit(path, isBare ? 1 : 0, out var handle));
        return new Repository(handle);
    }

    public static Repository Open(string path)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitPlainOpen(path, out var handle));
        return new Repository(handle);
    }

    public static Repository OpenWithOptions(string path, PlainOpenOptions options)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitPlainOpenWithOptions(path, options.Handle, out var handle));
        return new Repository(handle);
    }

    public static Repository Clone(string path, CloneOptions options)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitPlainClone(path, options.Handle, out var handle));
        return new Repository(handle);
    }

    public ReferenceIterator Branches()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryBranches(_handle, out var iter));
        return new ReferenceIterator(iter);
    }

    public Commit GetCommitObject(string hash)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCommitObject(
            _handle, hash,
            out var commitHash, out var msg, out var authorName, out var authorEmail, out var ts));
        return new Commit
        {
            Hash = NativeMethods.ConsumeGoString(commitHash)!,
            Message = NativeMethods.ConsumeGoString(msg)!,
            AuthorName = NativeMethods.ConsumeGoString(authorName)!,
            AuthorEmail = NativeMethods.ConsumeGoString(authorEmail)!,
            AuthorTimestamp = DateTimeOffset.FromUnixTimeSeconds(ts),
        };
    }

    public CommitIterator CommitObjects()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCommitObjects(_handle, out var iter));
        return new CommitIterator(iter);
    }

    public void CreateBranch(string name, string hash)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCreateBranch(_handle, name, hash));
    }

    public Remote CreateRemote(string name, string url)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCreateRemote(_handle, name, url, out var handle));
        return new Remote(handle);
    }

    public (string RefName, string Hash) CreateTag(string name, string hash, CreateTagOptions? opts = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCreateTag(_handle, name, hash, opts?.Handle ?? 0, out var outRefName, out var outHash));
        return (NativeMethods.ConsumeGoString(outRefName)!, NativeMethods.ConsumeGoString(outHash)!);
    }

    public void DeleteBranch(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryDeleteBranch(_handle, name));
    }

    public void DeleteObject(string hash)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryDeleteObject(_handle, hash));
    }

    public void DeleteRemote(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryDeleteRemote(_handle, name));
    }

    public void DeleteTag(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryDeleteTag(_handle, name));
    }

    public void Fetch(FetchOptions? o = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryFetch(_handle, o?.Handle ?? 0));
    }

    public void FetchContext(FetchOptions? o = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryFetchContext(_handle, o?.Handle ?? 0));
    }

    public (string RefName, string Hash) Head()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryHead(_handle, out var outRefName, out var outHash));
        return (NativeMethods.ConsumeGoString(outRefName)!, NativeMethods.ConsumeGoString(outHash)!);
    }

    public CommitIterator Log(LogOptions? o = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryLog(_handle, o?.Handle ?? 0, out var iter));
        return new CommitIterator(iter);
    }

    public void Merge(string refName, string hash, MergeOptions? options = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        var optsHandle = options?.Handle ?? 0;
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryMerge(_handle, refName, hash, optsHandle));
    }

    public ReferenceIterator Notes()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryNotes(_handle, out var iter));
        return new ReferenceIterator(iter);
    }

    public void Push(PushOptions? o = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryPush(_handle, o?.Handle ?? 0));
    }

    public void PushContext(PushOptions? o = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryPushContext(_handle, o?.Handle ?? 0));
    }

    public (string RefName, string Hash) Reference(string name, bool resolved)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryReference(_handle, name, resolved ? 1 : 0, out var outRefName, out var outHash));
        return (NativeMethods.ConsumeGoString(outRefName)!, NativeMethods.ConsumeGoString(outHash)!);
    }

    public ReferenceIterator References()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryReferences(_handle, out var iter));
        return new ReferenceIterator(iter);
    }

    public Remote GetRemote(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryRemote(_handle, name, out var h));
        return new Remote(h);
    }

    public string ResolveRevision(string input)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryResolveRevision(_handle, input, out var hash));
        return NativeMethods.ConsumeGoString(hash)!;
    }

    public (string RefName, string Hash) Tag(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryTag(_handle, name, out var outRefName, out var outHash));
        return (NativeMethods.ConsumeGoString(outRefName)!, NativeMethods.ConsumeGoString(outHash)!);
    }

    public ReferenceIterator Tags()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryTags(_handle, out var iter));
        return new ReferenceIterator(iter);
    }

    public Worktree GetWorktree()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryWorktree(_handle, out var h));
        return new Worktree(h);
    }

    public string[] Remotes()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryRemotes(_handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<string[]>(json) ?? [];
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitRepositoryFree(_handle);
        _handle = 0;
    }
}
