// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

/// <summary>
/// A signing key used to GPG-sign git commits and tags.
/// Use <see cref="FromPGPKey"/> to load an armored PGP private key, then pass the instance
/// to <see cref="CommitOptions"/> or <see cref="CreateTagOptions"/> via <c>SetSigner</c>.
/// </summary>
public sealed class Signer : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Signer(long handle) => _handle = handle;
    internal long Handle => _handle;

    /// <summary>Loads a PGP signing key from an ASCII-armored private key string.</summary>
    public static Signer FromPGPKey(string armoredKey, string passphrase = "")
    {
        NativeMethods.ThrowIfError(NativeMethods.GitSignerNewPGP(armoredKey, passphrase, out var handle));
        return new Signer(handle);
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitSignerFree(_handle);
        _handle = 0;
    }
}
