// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable

namespace GoGit.Interop;

public sealed class Submodule : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Submodule(long handle) => _handle = handle;

    public void Init()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleInit(_handle));
    }

    public Repository GetRepository()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleRepository(_handle, out var h));
        return new Repository(h);
    }

    public void Update(SubmoduleUpdateOptions? o = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleUpdate(_handle, o?.Handle ?? 0));
    }

    public void UpdateContext(SubmoduleUpdateOptions? o = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleUpdateContext(_handle, o?.Handle ?? 0));
    }

    public string Name
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleConfigName(_handle, out var namePtr));
            return NativeMethods.ConsumeGoString(namePtr)!;
        }
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitSubmoduleFree(_handle);
        _handle = 0;
    }
}
