// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json;

namespace GoGit.Interop;

public sealed class Submodule : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Submodule(long handle) => _handle = handle;
    internal long Handle => _handle;

    public void Init()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleInit(_handle));
    }

    public Repository GetRepository()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleRepository(_handle, out var resultHandle));
        return new Repository(resultHandle);
    }

    public void Update(SubmoduleUpdateOptions? o = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleUpdate(_handle, o?.Handle ?? 0));
    }

    public void UpdateContext(SubmoduleUpdateOptions? o = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleUpdateContext(_handle, o?.Handle ?? 0));
    }

    public string Name
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleConfigName(_handle, out var namePtr));
            return NativeMethods.ConsumeGoString(namePtr)!;
        }
    }

    public SubmoduleConfig GetConfig()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleConfig(_handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<SubmoduleConfig>(json)!;
    }

    public SubmoduleStatusInfo GetStatus()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleStatus(_handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<SubmoduleStatusInfo>(json)!;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitSubmoduleFree(_handle);
        _handle = 0;
    }
}
