// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable

namespace GoGit.Interop;

public sealed class Tag : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Tag(long handle) => _handle = handle;
    internal long Handle => _handle;

    public Blob GetBlob()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTagBlob(_handle, out var resultHandle));
        return new Blob(resultHandle);
    }

    public Commit GetCommit()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTagCommit(_handle, out var resultHandle));
        return new Commit(resultHandle);
    }

    public string ID()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTagID(_handle, out var hash));
        return NativeMethods.ConsumeGoString(hash)!;
    }

    public string String()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTagString(_handle, out var s));
        return NativeMethods.ConsumeGoString(s)!;
    }

    public Tree GetTree()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTagTree(_handle, out var resultHandle));
        return new Tree(resultHandle);
    }

    public int Type()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTagType(_handle, out var val));
        return val;
    }

    public void Verify(string armoredKeyRing)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTagVerify(_handle, armoredKeyRing));
    }

    public string Hash
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitTagGetHash(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public string Name
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitTagGetName(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public string Message
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitTagGetMessage(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public string Signature
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitTagGetSignature(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public string Target
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitTagGetTarget(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitTagFree(_handle);
        _handle = 0;
    }
}
