// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json;

namespace GoGit.Interop;

/// <summary>A git tree object representing a directory snapshot. Provides file enumeration, entry lookup, and diff operations. Wraps <c>*object.Tree</c> from go-git.</summary>
public sealed class Tree : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Tree(long handle) => _handle = handle;
    internal long Handle => _handle;

    /// <summary>Returns the list of file changes between this tree and <paramref name="to"/>. Pass <c>null</c> to diff against the empty tree.</summary>
    public DiffChange[] Diff(Tree? to = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTreeDiff(_handle, to?.Handle ?? 0, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<DiffChange[]>(json) ?? [];
    }

    public File File(string path)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTreeFile(_handle, path, out var resultHandle));
        return new File(resultHandle);
    }

    /// <summary>Returns an iterator over all files reachable from this tree.</summary>
    public FileIterator Files()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTreeFiles(_handle, out var iter));
        return new FileIterator(iter);
    }

    /// <summary>Finds the tree entry at the given <paramref name="path"/>, searching recursively through subtrees.</summary>
    public TreeEntryInfo FindEntry(string path)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTreeFindEntry(_handle, path, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<TreeEntryInfo>(json)!;
    }

    public string ID()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTreeID(_handle, out var hash));
        return NativeMethods.ConsumeGoString(hash)!;
    }

    /// <summary>Returns the unified diff between this tree and <paramref name="to"/>. Pass <c>null</c> to diff against the empty tree.</summary>
    public string GetPatch(Tree? to = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTreePatch(_handle, to?.Handle ?? 0, out var patchPtr));
        return NativeMethods.ConsumeGoString(patchPtr)!;
    }

    public long Size(string path)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTreeSize(_handle, path, out var val));
        return val;
    }

    public Tree GetSubtree(string path)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTreeTree(_handle, path, out var resultHandle));
        return new Tree(resultHandle);
    }

    public int Type()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitTreeType(_handle, out var val));
        return val;
    }

    /// <summary>The SHA-1 hash of this tree.</summary>
    public string Hash
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitTreeGetHash(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitTreeFree(_handle);
        _handle = 0;
    }
}
