// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable

namespace GoGitDotNet;

/// <summary>A git blob object representing raw file contents. Wraps <c>*object.Blob</c> from go-git.</summary>
public sealed class Blob : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Blob(long handle) => _handle = handle;
    internal long Handle => _handle;

    public string ID()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitBlobID(_handle, out var hash));
        return NativeMethods.ConsumeGoString(hash)!;
    }

    /// <summary>Returns the full contents of this blob as a UTF-8 string.</summary>
    public string Contents()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitBlobReader(_handle, out var dataPtr));
        return NativeMethods.ConsumeGoString(dataPtr)!;
    }

    public int Type()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitBlobType(_handle, out var val));
        return val;
    }

    /// <summary>The SHA-1 hash of this blob.</summary>
    public string Hash
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitBlobGetHash(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    /// <summary>The size of the blob contents in bytes.</summary>
    public long Size
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitBlobGetSize(_handle, out var val));
            return val;
        }
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitBlobFree(_handle);
        _handle = 0;
    }
}
