// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json;

namespace GoGitDotNet;

/// <summary>A git commit object. Provides access to the hash, message, author, committer, tree, parents, and diff operations. Wraps <c>*object.Commit</c> from go-git.</summary>
public sealed class Commit : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Commit(long handle) => _handle = handle;
    internal long Handle => _handle;

    public File File(string path)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitFile(_handle, path, out var resultHandle));
        return new File(resultHandle);
    }

    /// <summary>Returns an iterator over all files in the commit's tree.</summary>
    public FileIterator Files()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitFiles(_handle, out var iter));
        return new FileIterator(iter);
    }

    public string ID()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitID(_handle, out var hash));
        return NativeMethods.ConsumeGoString(hash)!;
    }

    public bool IsAncestor(Commit other)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitIsAncestor(_handle, other.Handle, out var val));
        return val != 0;
    }

    public bool Less(Commit rhs)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitLess(_handle, rhs.Handle, out var val));
        return val != 0;
    }

    /// <summary>Returns the SHA-1 hashes of common ancestor commits shared by this commit and <paramref name="other"/>.</summary>
    public string[] MergeBase(Commit other)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitMergeBase(_handle, other.Handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<string[]>(json) ?? [];
    }

    public int NumParents()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitNumParents(_handle, out var val));
        return val;
    }

    public Commit Parent(int i)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitParent(_handle, i, out var resultHandle));
        return new Commit(resultHandle);
    }

    /// <summary>Returns an iterator over the parent commits.</summary>
    public CommitIterator Parents()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitParents(_handle, out var iter));
        return new CommitIterator(iter);
    }

    /// <summary>Returns the unified diff between this commit and <paramref name="to"/>. Pass <c>null</c> to diff against the empty tree.</summary>
    public string GetPatch(Commit? to = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitPatch(_handle, to?.Handle ?? 0, out var patchPtr));
        return NativeMethods.ConsumeGoString(patchPtr)!;
    }

    /// <summary>Returns per-file line addition/deletion statistics for this commit.</summary>
    public FileStat[] Stats()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitStats(_handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<FileStat[]>(json) ?? [];
    }

    public string String()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitString(_handle, out var s));
        return NativeMethods.ConsumeGoString(s)!;
    }

    /// <summary>Returns the root tree of this commit.</summary>
    public Tree GetTree()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitTree(_handle, out var resultHandle));
        return new Tree(resultHandle);
    }

    public int Type()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitType(_handle, out var val));
        return val;
    }

    /// <summary>Verifies the PGP signature of this commit against <paramref name="armoredKeyRing"/>. Throws if the signature is invalid or missing.</summary>
    public void Verify(string armoredKeyRing)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitVerify(_handle, armoredKeyRing));
    }

    public string AuthorName
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitCommitAuthorName(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public string AuthorEmail
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitCommitAuthorEmail(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public DateTimeOffset AuthorWhen
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitCommitAuthorWhen(_handle, out var ts));
            return DateTimeOffset.FromUnixTimeSeconds(ts);
        }
    }

    public string CommitterName
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitCommitCommitterName(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public string CommitterEmail
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitCommitCommitterEmail(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public DateTimeOffset CommitterWhen
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitCommitCommitterWhen(_handle, out var ts));
            return DateTimeOffset.FromUnixTimeSeconds(ts);
        }
    }

    /// <summary>The SHA-1 hash of this commit.</summary>
    public string Hash
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitCommitGetHash(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public string MergeTag
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitCommitGetMergeTag(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public string Signature
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitCommitGetSignature(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    /// <summary>The full commit message.</summary>
    public string Message
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitCommitGetMessage(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public string TreeHash
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitCommitGetTreeHash(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public string Encoding
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitCommitGetEncoding(_handle, out var ptr));
            return NativeMethods.ConsumeGoString(ptr)!;
        }
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitCommitFree(_handle);
        _handle = 0;
    }
}
