// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json;

namespace GoGitDotNet;

/// <summary>A git repository. Provides access to commits, branches, tags, remotes, and worktree operations. Wraps <c>*git.Repository</c> from go-git.</summary>
public sealed class Repository : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Repository(long handle) => _handle = handle;
    internal long Handle => _handle;

    /// <summary>Initialises a new git repository at <paramref name="path"/>.</summary>
    public static Repository Init(string path, bool isBare = false)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitPlainInit(path, isBare ? 1 : 0, out var handle));
        return new Repository(handle);
    }

    /// <summary>Opens an existing git repository at <paramref name="path"/>.</summary>
    public static Repository Open(string path)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitPlainOpen(path, out var handle));
        return new Repository(handle);
    }

    /// <summary>Opens an existing git repository at <paramref name="path"/> with additional options.</summary>
    public static Repository OpenWithOptions(string path, PlainOpenOptions options)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitPlainOpenWithOptions(path, options.Handle, out var handle));
        return new Repository(handle);
    }

    /// <summary>Clones the repository described by <paramref name="options"/> into <paramref name="path"/> on disk.</summary>
    public static Repository Clone(string path, CloneOptions options)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitPlainClone(path, options.Handle, out var handle));
        return new Repository(handle);
    }

    /// <summary>Clones the repository described by <paramref name="options"/> entirely into memory. No files are written to disk.</summary>
    public static Repository CloneInMemory(CloneOptions options)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitCloneInMemory(options.Handle, out var handle));
        return new Repository(handle);
    }

    public Blob BlobObject(string h)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryBlobObject(_handle, h, out var resultHandle));
        return new Blob(resultHandle);
    }

    /// <summary>Returns an iterator over all blob objects in the object store.</summary>
    public BlobIterator BlobObjects()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryBlobObjects(_handle, out var iter));
        return new BlobIterator(iter);
    }

    /// <summary>Returns the configuration for the branch named <paramref name="name"/>.</summary>
    public BranchConfig GetBranch(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryBranch(_handle, name, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<BranchConfig>(json)!;
    }

    /// <summary>Returns an iterator over all branch references.</summary>
    public ReferenceIterator Branches()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryBranches(_handle, out var iter));
        return new ReferenceIterator(iter);
    }

    public Commit CommitObject(string h)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCommitObject(_handle, h, out var resultHandle));
        return new Commit(resultHandle);
    }

    /// <summary>Returns an iterator over all commit objects in the object store.</summary>
    public CommitIterator CommitObjects()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCommitObjects(_handle, out var iter));
        return new CommitIterator(iter);
    }

    /// <summary>Returns a subset of the repository's git configuration (core, user identity, default branch).</summary>
    public GitConfig Config()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryConfig(_handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<GitConfig>(json)!;
    }

    /// <inheritdoc cref="Config"/>
    [Obsolete("Use Config instead.")]
    public GitConfig GetConfig() => Config();

    /// <summary>Creates a new local branch pointing at <paramref name="hash"/>.</summary>
    public void CreateBranch(string name, string hash)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCreateBranch(_handle, name, hash));
    }

    /// <summary>Adds a new remote with the given <paramref name="name"/> and <paramref name="url"/> to the repository configuration.</summary>
    public Remote CreateRemote(string name, string url)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCreateRemote(_handle, name, url, out var handle));
        return new Remote(handle);
    }

    /// <summary>Creates a temporary anonymous remote for <paramref name="url"/>. The remote is not saved to the repository configuration.</summary>
    public Remote CreateRemoteAnonymous(string url)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCreateRemoteAnonymous(_handle, url, out var handle));
        return new Remote(handle);
    }

    public (string RefName, string Hash) CreateTag(string name, string hash, CreateTagOptions? opts = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCreateTag(_handle, name, hash, opts?.Handle ?? 0, out var outRefName, out var outHash));
        return (NativeMethods.ConsumeGoString(outRefName)!, NativeMethods.ConsumeGoString(outHash)!);
    }

    /// <summary>Deletes a local branch by name.</summary>
    public void DeleteBranch(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryDeleteBranch(_handle, name));
    }

    /// <summary>Removes an object from the object store by hash.</summary>
    public void DeleteObject(string hash)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryDeleteObject(_handle, hash));
    }

    /// <summary>Removes a remote configuration by name.</summary>
    public void DeleteRemote(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryDeleteRemote(_handle, name));
    }

    /// <summary>Deletes a tag by name.</summary>
    public void DeleteTag(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryDeleteTag(_handle, name));
    }

    /// <summary>Fetches from all configured remotes.</summary>
    public void Fetch(FetchOptions? o = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryFetch(_handle, o?.Handle ?? 0));
    }

    /// <summary>Fetches from all configured remotes using a background context.</summary>
    public void FetchContext(FetchOptions? o = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryFetchContext(_handle, o?.Handle ?? 0));
    }

    /// <summary>Returns the HEAD reference as a (refName, hash) pair.</summary>
    public (string RefName, string Hash) Head()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryHead(_handle, out var outRefName, out var outHash));
        return (NativeMethods.ConsumeGoString(outRefName)!, NativeMethods.ConsumeGoString(outHash)!);
    }

    /// <summary>Returns an iterator over commits reachable from the options starting point.</summary>
    public CommitIterator Log(LogOptions? o = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryLog(_handle, o?.Handle ?? 0, out var iter));
        return new CommitIterator(iter);
    }

    /// <summary>Merges the commit identified by <paramref name="hash"/> into the current branch.</summary>
    public void Merge(string refName, string hash, MergeOptions? options = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        var optsHandle = options?.Handle ?? 0;
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryMerge(_handle, refName, hash, optsHandle));
    }

    /// <summary>Returns an iterator over all note references.</summary>
    public ReferenceIterator Notes()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryNotes(_handle, out var iter));
        return new ReferenceIterator(iter);
    }

    /// <summary>Pushes local changes to the remote.</summary>
    public void Push(PushOptions? o = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryPush(_handle, o?.Handle ?? 0));
    }

    /// <summary>Pushes local changes to the remote using a background context.</summary>
    public void PushContext(PushOptions? o = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryPushContext(_handle, o?.Handle ?? 0));
    }

    /// <summary>Looks up a single reference by name.</summary>
    public (string RefName, string Hash) Reference(string name, bool resolved)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryReference(_handle, name, resolved ? 1 : 0, out var outRefName, out var outHash));
        return (NativeMethods.ConsumeGoString(outRefName)!, NativeMethods.ConsumeGoString(outHash)!);
    }

    /// <summary>Returns an iterator over all references in the repository.</summary>
    public ReferenceIterator References()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryReferences(_handle, out var iter));
        return new ReferenceIterator(iter);
    }

    public Remote Remote(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryRemote(_handle, name, out var resultHandle));
        return new Remote(resultHandle);
    }

    /// <summary>Resolves a revision string (e.g. <c>HEAD~2</c>) to a commit hash.</summary>
    public string ResolveRevision(string input)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryResolveRevision(_handle, input, out var hash));
        return NativeMethods.ConsumeGoString(hash)!;
    }

    public (string RefName, string Hash) Tag(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryTag(_handle, name, out var outRefName, out var outHash));
        return (NativeMethods.ConsumeGoString(outRefName)!, NativeMethods.ConsumeGoString(outHash)!);
    }

    public Tag GetTagObject(string h)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryTagObject(_handle, h, out var resultHandle));
        return new Tag(resultHandle);
    }

    /// <summary>Returns an iterator over all annotated tag objects in the object store.</summary>
    public TagIterator TagObjects()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryTagObjects(_handle, out var iter));
        return new TagIterator(iter);
    }

    /// <summary>Returns an iterator over all tag references.</summary>
    public ReferenceIterator Tags()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryTags(_handle, out var iter));
        return new ReferenceIterator(iter);
    }

    public Tree GetTreeObject(string h)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryTreeObject(_handle, h, out var resultHandle));
        return new Tree(resultHandle);
    }

    /// <summary>Returns an iterator over all tree objects in the object store.</summary>
    public TreeIterator TreeObjects()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryTreeObjects(_handle, out var iter));
        return new TreeIterator(iter);
    }

    public Worktree Worktree()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryWorktree(_handle, out var resultHandle));
        return new Worktree(resultHandle);
    }

    /// <summary>Returns the names of all configured remotes.</summary>
    public string[] Remotes()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryRemotes(_handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<string[]>(json) ?? [];
    }

    /// <summary>Returns line-by-line blame information for the file at <paramref name="path"/> as of the given <paramref name="commit"/>.</summary>
    public static BlameResult Blame(Commit commit, string path)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitBlame(commit.Handle, path, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<BlameResult>(json)!;
    }

    /// <summary>Writes <paramref name="content"/> as a blob object to the object store. Returns its SHA-1 hash.</summary>
    public string StoreBlob(byte[] content)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        var b64 = Convert.ToBase64String(content);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryStoreBlob(_handle, b64, out var hashPtr));
        return NativeMethods.ConsumeGoString(hashPtr)!;
    }

    /// <summary>Writes UTF-8 encoded <paramref name="text"/> as a blob object to the object store. Returns its SHA-1 hash.</summary>
    public string StoreBlob(string text) => StoreBlob(System.Text.Encoding.UTF8.GetBytes(text));

    /// <summary>Returns the direct entries of the tree identified by <paramref name="treeHash"/>.</summary>
    public TreeEntryInfo[] TreeEntries(string treeHash)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryGetTreeEntries(_handle, treeHash, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<TreeEntryInfo[]>(json) ?? [];
    }

    /// <inheritdoc cref="TreeEntries"/>
    [Obsolete("Use TreeEntries instead.")]
    public TreeEntryInfo[] GetTreeEntries(string treeHash) => TreeEntries(treeHash);

    /// <inheritdoc cref="BlobObject"/>
    [Obsolete("Use BlobObject instead.")]
    public Blob GetBlobObject(string hash) => BlobObject(hash);

    /// <inheritdoc cref="CommitObject"/>
    [Obsolete("Use CommitObject instead.")]
    public Commit GetCommitObject(string hash) => CommitObject(hash);

    /// <summary>Writes a tree object built from <paramref name="entries"/> to the object store. Returns its SHA-1 hash.</summary>
    /// <remarks>Entries are automatically sorted in git tree order (directories sort as <c>name + "/"</c>).</remarks>
    public string StoreTree(IEnumerable<TreeEntryInfo> entries)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        var sorted = entries.OrderBy(e =>
            e.Mode is TreeEntryMode.Directory or TreeEntryMode.GitLink ? e.Name + "/" : e.Name,
            StringComparer.Ordinal);
        var json = JsonSerializer.Serialize(sorted);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryStoreTree(_handle, json, out var hashPtr));
        return NativeMethods.ConsumeGoString(hashPtr)!;
    }

    /// <summary>
    /// Writes a commit object directly to the object store without touching the worktree.
    /// Returns the SHA-1 hash of the new commit.
    /// </summary>
    public string StoreCommit(
        string treeHash,
        string[] parentHashes,
        string authorName, string authorEmail,
        string committerName, string committerEmail,
        string message,
        DateTimeOffset when)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        var parentsJson = JsonSerializer.Serialize(parentHashes);
        var ts = when.ToUnixTimeSeconds();
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryStoreCommit(
            _handle, treeHash, parentsJson,
            authorName, authorEmail,
            committerName, committerEmail,
            message, ts, out var hashPtr));
        return NativeMethods.ConsumeGoString(hashPtr)!;
    }

    /// <summary>Updates (or creates) the reference <paramref name="refName"/> to point at <paramref name="hash"/>.</summary>
    public void SetReference(string refName, string hash)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositorySetReference(_handle, refName, hash));
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitRepositoryFree(_handle);
        _handle = 0;
    }
}
