// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGitDotNet;

/// <summary>Options for a go-git <c>CheckoutOptions</c> operation. Use the fluent <c>Set*</c> methods to configure, then pass to the corresponding repository method.</summary>
public sealed class CheckoutOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    /// <summary>Initialises a new <see cref="CheckoutOptions"/> with default values.</summary>
    public CheckoutOptions()
    {
        NativeMethods.GitCheckoutOptionsNew(out _handle);
    }

    /// <summary>Sets the <c>Hash</c> option.</summary>
    public CheckoutOptions SetHash(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCheckoutOptionsSetHash(_handle, value));
        return this;
    }

    /// <summary>Sets the <c>Branch</c> option.</summary>
    public CheckoutOptions SetBranch(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCheckoutOptionsSetBranch(_handle, value));
        return this;
    }

    /// <summary>Sets the <c>Create</c> option.</summary>
    public CheckoutOptions SetCreate(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCheckoutOptionsSetCreate(_handle, value ? 1 : 0));
        return this;
    }

    /// <summary>Sets the <c>Force</c> option.</summary>
    public CheckoutOptions SetForce(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCheckoutOptionsSetForce(_handle, value ? 1 : 0));
        return this;
    }

    /// <summary>Sets the <c>Keep</c> option.</summary>
    public CheckoutOptions SetKeep(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCheckoutOptionsSetKeep(_handle, value ? 1 : 0));
        return this;
    }

    /// <summary>Sets the <c>SparseCheckoutDirectories</c> option.</summary>
    public CheckoutOptions SetSparseCheckoutDirectories(string[] value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCheckoutOptionsSetSparseCheckoutDirectories(_handle, System.Text.Json.JsonSerializer.Serialize(value)));
        return this;
    }

    /// <summary>Releases the underlying go-git options object.</summary>
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitCheckoutOptionsFree(_handle);
        _handle = 0;
    }
}
