// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGitDotNet;

/// <summary>Options for a go-git <c>ListOptions</c> operation. Use the fluent <c>Set*</c> methods to configure, then pass to the corresponding repository method.</summary>
public sealed class ListOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    /// <summary>Initialises a new <see cref="ListOptions"/> with default values.</summary>
    public ListOptions()
    {
        NativeMethods.GitListOptionsNew(out _handle);
    }

    /// <summary>Sets the <c>Auth</c> option.</summary>
    public ListOptions SetAuth(Auth value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitListOptionsSetAuth(_handle, value.Handle));
        return this;
    }

    /// <summary>Sets the <c>InsecureSkipTLS</c> option.</summary>
    public ListOptions SetInsecureSkipTLS(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitListOptionsSetInsecureSkipTLS(_handle, value ? 1 : 0));
        return this;
    }

    /// <summary>Sets the <c>PeelingOption</c> option.</summary>
    public ListOptions SetPeelingOption(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitListOptionsSetPeelingOption(_handle, value));
        return this;
    }

    /// <summary>Sets the <c>Timeout</c> option.</summary>
    public ListOptions SetTimeout(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitListOptionsSetTimeout(_handle, value));
        return this;
    }

    /// <summary>Sets the <c>Proxy</c> option.</summary>
    public ListOptions SetProxy(string url, string? username = null, string? password = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitListOptionsSetProxy(_handle, url, username ?? "", password ?? ""));
        return this;
    }

    /// <summary>Releases the underlying go-git options object.</summary>
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitListOptionsFree(_handle);
        _handle = 0;
    }
}
