// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGitDotNet;

/// <summary>Options for a go-git <c>ResetOptions</c> operation. Use the fluent <c>Set*</c> methods to configure, then pass to the corresponding repository method.</summary>
public sealed class ResetOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    /// <summary>Initialises a new <see cref="ResetOptions"/> with default values.</summary>
    public ResetOptions()
    {
        NativeMethods.GitResetOptionsNew(out _handle);
    }

    /// <summary>Sets the <c>Commit</c> option.</summary>
    public ResetOptions SetCommit(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitResetOptionsSetCommit(_handle, value));
        return this;
    }

    /// <summary>Sets the <c>Mode</c> option.</summary>
    public ResetOptions SetMode(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitResetOptionsSetMode(_handle, value));
        return this;
    }

    /// <summary>Sets the <c>Files</c> option.</summary>
    public ResetOptions SetFiles(string[] value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitResetOptionsSetFiles(_handle, System.Text.Json.JsonSerializer.Serialize(value)));
        return this;
    }

    /// <summary>Sets the <c>SparseDirs</c> option.</summary>
    public ResetOptions SetSparseDirs(string[] value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitResetOptionsSetSparseDirs(_handle, System.Text.Json.JsonSerializer.Serialize(value)));
        return this;
    }

    /// <summary>Sets the <c>SkipSparseDirValidation</c> option.</summary>
    public ResetOptions SetSkipSparseDirValidation(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitResetOptionsSetSkipSparseDirValidation(_handle, value ? 1 : 0));
        return this;
    }

    /// <summary>Releases the underlying go-git options object.</summary>
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitResetOptionsFree(_handle);
        _handle = 0;
    }
}
