// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGitDotNet;

/// <summary>Options for a go-git <c>UploadPackOptions</c> operation. Use the fluent <c>Set*</c> methods to configure, then pass to the corresponding repository method.</summary>
public sealed class UploadPackOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    /// <summary>Initialises a new <see cref="UploadPackOptions"/> with default values.</summary>
    public UploadPackOptions()
    {
        NativeMethods.GitUploadPackOptionsNew(out _handle);
    }

    /// <summary>Sets the <c>GitProtocol</c> option.</summary>
    public UploadPackOptions SetGitProtocol(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitUploadPackOptionsSetGitProtocol(_handle, value));
        return this;
    }

    /// <summary>Sets the <c>AdvertiseRefs</c> option.</summary>
    public UploadPackOptions SetAdvertiseRefs(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitUploadPackOptionsSetAdvertiseRefs(_handle, value ? 1 : 0));
        return this;
    }

    /// <summary>Sets the <c>StatelessRPC</c> option.</summary>
    public UploadPackOptions SetStatelessRPC(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitUploadPackOptionsSetStatelessRPC(_handle, value ? 1 : 0));
        return this;
    }

    /// <summary>Releases the underlying go-git options object.</summary>
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitUploadPackOptionsFree(_handle);
        _handle = 0;
    }
}
