package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const genHeader = "// Code generated by gogit-interop/generate. DO NOT EDIT.\npackage main\n"

func generateGo(pkg *Package, outputDir string) error {
	if err := generateAuthGo(outputDir); err != nil {
		return fmt.Errorf("generating auth: %w", err)
	}
	if err := generateSigningGo(outputDir); err != nil {
		return fmt.Errorf("generating signing: %w", err)
	}
	if err := generateOptionsGo(pkg, outputDir); err != nil {
		return fmt.Errorf("generating options: %w", err)
	}
	if err := generateHandleTypesGo(pkg, outputDir); err != nil {
		return fmt.Errorf("generating handle types: %w", err)
	}
	if err := generateIteratorsGo(outputDir); err != nil {
		return fmt.Errorf("generating iterators: %w", err)
	}
	return nil
}

func writeGenFile(outputDir, filename, content string) error {
	path := filepath.Join(outputDir, filename)
	return os.WriteFile(path, []byte(content), 0644)
}

func generateHandleTypesGo(pkg *Package, outputDir string) error {
	repoFuncs := findFunctions(pkg, "Repository")
	otherFuncs := findNonRepoFunctions(pkg)

	for _, ht := range pkg.Types {
		var b strings.Builder
		b.WriteString(genHeader)
		b.WriteString("\n/*\n#include <stdlib.h>\n*/\nimport \"C\"\n")

		imports := collectImports(&ht, ht.GoName == "Repository")
		writeImports(&b, imports)
		b.WriteString("\n")

		if ht.GoName == "Repository" {
			for _, fn := range repoFuncs {
				generateTopLevelFunction(&b, fn)
			}
			for _, fn := range otherFuncs {
				generateTopLevelFunction(&b, fn)
			}
		}

		for _, m := range ht.Methods {
			generateGenericMethod(&b, &ht, m)
		}

		generateExtraMethodsGo(&b, &ht)
		generateHandleFree(&b, &ht)
		writeSuppressImports(&b, &ht, imports)

		filename := strings.ToLower(ht.GoName) + "_gen.go"
		if err := writeGenFile(outputDir, filename, b.String()); err != nil {
			return err
		}
	}
	return nil
}

func findFunctions(pkg *Package, typeName string) []Function {
	var result []Function
	for _, fn := range pkg.Functions {
		for _, r := range fn.Returns {
			if r.Mapping.HandleType == typeName {
				result = append(result, fn)
				break
			}
		}
	}
	return result
}

func findNonRepoFunctions(pkg *Package) []Function {
	var result []Function
	for _, fn := range pkg.Functions {
		isRepo := false
		for _, r := range fn.Returns {
			if r.Mapping.HandleType == "Repository" {
				isRepo = true
				break
			}
		}
		if !isRepo {
			result = append(result, fn)
		}
	}
	return result
}

func collectImports(ht *HandleType, isRepo bool) []string {
	importSet := map[string]bool{
		"encoding/json": true,
	}

	addPackageImport(importSet, ht.ImportPath)

	for _, m := range ht.Methods {
		addMethodImports(importSet, m)
	}

	if isRepo {
		importSet["\"context\""] = true
		addPackageImport(importSet, "github.com/go-git/go-git/v6/config")
		addPackageImport(importSet, "github.com/go-git/go-git/v6/plumbing")
		addPackageImport(importSet, "github.com/go-git/go-git/v6/plumbing/transport")
	}

	var imports []string
	for imp := range importSet {
		imports = append(imports, imp)
	}
	return imports
}

func addMethodImports(importSet map[string]bool, m Method) {
	if m.HasContext {
		importSet["\"context\""] = true
	}
	for _, p := range m.Params {
		addMappingImports(importSet, p.Mapping)
	}
	for _, r := range m.Returns {
		addMappingImports(importSet, r.Mapping)
	}
}

func addPackageImport(importSet map[string]bool, pkgPath string) {
	alias := importAlias(pkgPath)
	parts := strings.Split(pkgPath, "/")
	lastSegment := parts[len(parts)-1]
	if alias == lastSegment {
		importSet[fmt.Sprintf("\"%s\"", pkgPath)] = true
	} else {
		importSet[fmt.Sprintf("%s \"%s\"", alias, pkgPath)] = true
	}
}

func addMappingImports(importSet map[string]bool, m TypeMapping) {
	switch m.Kind {
	case MappingHash, MappingReferenceName, MappingRevision, MappingReference:
		addPackageImport(importSet, "github.com/go-git/go-git/v6/plumbing")
	case MappingAuth:
		addPackageImport(importSet, "github.com/go-git/go-git/v6/plumbing/transport")
	case MappingHandle, MappingOptions:
		if m.QualifiedName != "" {
			qname := strings.TrimPrefix(m.QualifiedName, "*")
			lastDot := strings.LastIndex(qname, ".")
			if lastDot > 0 {
				pkgPath := qname[:lastDot]
				addPackageImport(importSet, pkgPath)
			}
		}
	case MappingIterator:
		if strings.Contains(m.GoType, "object") {
			addPackageImport(importSet, "github.com/go-git/go-git/v6/plumbing/object")
		}
		if strings.Contains(m.GoType, "storer") {
			addPackageImport(importSet, "github.com/go-git/go-git/v6/plumbing/storer")
		}
	case MappingEnum:
		if m.QualifiedName != "" {
			lastDot := strings.LastIndex(m.QualifiedName, ".")
			if lastDot > 0 {
				addPackageImport(importSet, m.QualifiedName[:lastDot])
			}
		}
	case MappingTime, MappingDuration:
		importSet["\"time\""] = true
	case MappingStringSlice:
		importSet["\"encoding/json\""] = true
		if m.QualifiedName != "" {
			lastDot := strings.LastIndex(m.QualifiedName, ".")
			if lastDot > 0 {
				addPackageImport(importSet, m.QualifiedName[:lastDot])
			}
		}
	}
}

func writeImports(b *strings.Builder, imports []string) {
	if len(imports) == 0 {
		return
	}
	b.WriteString("import (\n")
	for _, imp := range imports {
		if strings.HasPrefix(imp, "\"") || strings.Contains(imp, " \"") {
			fmt.Fprintf(b, "\t%s\n", imp)
		} else {
			fmt.Fprintf(b, "\t\"%s\"\n", imp)
		}
	}
	b.WriteString(")\n")
}

func generateTopLevelFunction(b *strings.Builder, fn Function) {
	fmt.Fprintf(b, "//export %s\n", fn.CName)

	var params []string
	for _, p := range fn.Params {
		params = append(params, fmt.Sprintf("%s %s", p.CName, p.Mapping.CType))
	}

	hasHandleReturn := false
	for _, r := range fn.Returns {
		if !r.IsError && r.Mapping.Kind == MappingHandle {
			params = append(params, "handleOut *C.longlong")
			hasHandleReturn = true
		}
	}

	fmt.Fprintf(b, "func %s(%s) *C.char {\n", fn.CName, strings.Join(params, ", "))

	generateFunctionBody(b, fn, hasHandleReturn)

	b.WriteString("}\n\n")
}

func isSpecialFunction(name string) bool {
	return name == "Clone" || name == "CloneContext"
}

func generateFunctionBody(b *strings.Builder, fn Function, hasHandleReturn bool) {
	switch fn.GoName {
	case "Clone", "CloneContext":
		optsParam := fn.Params[0].CName
		goCall := "git.Clone"
		if fn.HasContext {
			goCall = "git.CloneContext"
		}
		fmt.Fprintf(b, "\topts, ok := loadHandle[*git.CloneOptions](int64(%s))\n", optsParam)
		b.WriteString("\tif !ok {\n\t\treturn C.CString(\"invalid CloneOptions handle\")\n\t}\n")
		b.WriteString("\tstorer := memory.NewStorage()\n")
		b.WriteString("\tvar wt billy.Filesystem\n")
		b.WriteString("\tif !opts.Bare {\n\t\twt = memfs.New()\n\t}\n")
		if fn.HasContext {
			fmt.Fprintf(b, "\trepo, err := %s(context.Background(), storer, wt, opts)\n", goCall)
		} else {
			fmt.Fprintf(b, "\trepo, err := %s(storer, wt, opts)\n", goCall)
		}
		b.WriteString("\tif err != nil {\n\t\treturn toCError(err)\n\t}\n")
		b.WriteString("\t*handleOut = C.longlong(storeHandle(repo))\n")
		b.WriteString("\treturn nil\n")
	default:
		generateGenericFunctionBody(b, fn, hasHandleReturn)
	}
}

func generateGenericFunctionBody(b *strings.Builder, fn Function, hasHandleReturn bool) {
	var goArgs []string
	if fn.HasContext {
		goArgs = append(goArgs, "context.Background()")
	}
	for _, p := range fn.Params {
		goArgs = append(goArgs, convertParamCToGo(p))
	}

	var resultVars []string
	hasError := false
	for _, r := range fn.Returns {
		if r.IsError {
			hasError = true
			continue
		}
		resultVars = append(resultVars, "result")
	}
	if hasError {
		resultVars = append(resultVars, "err")
	}

	if len(resultVars) > 0 {
		fmt.Fprintf(b, "\t%s := git.%s(%s)\n", strings.Join(resultVars, ", "), fn.GoName, strings.Join(goArgs, ", "))
	} else {
		fmt.Fprintf(b, "\tgit.%s(%s)\n", fn.GoName, strings.Join(goArgs, ", "))
	}

	if hasError {
		b.WriteString("\tif err != nil {\n\t\treturn toCError(err)\n\t}\n")
	}

	if hasHandleReturn {
		b.WriteString("\t*handleOut = C.longlong(storeHandle(result))\n")
	}

	b.WriteString("\treturn nil\n")
}

func generateGenericMethod(b *strings.Builder, ht *HandleType, m Method) {
	if isOverrideMethod(ht.GoName, m.GoName) {
		generateOverrideMethod(b, ht, m)
		return
	}

	fmt.Fprintf(b, "//export %s\n", m.CName)

	receiverParam := strings.ToLower(ht.GoName[:1]) + "Handle"
	var params []string
	params = append(params, fmt.Sprintf("%s C.longlong", receiverParam))

	for _, p := range m.Params {
		params = append(params, fmt.Sprintf("%s %s", p.CName, p.Mapping.CType))
	}

	var outParams []outParam
	usedNames := map[string]int{}
	for i, r := range m.Returns {
		if r.IsError {
			continue
		}
		ops := outParamsForReturn(r, i)
		for _, op := range ops {
			if cnt, exists := usedNames[op.name]; exists {
				op.name = fmt.Sprintf("%s%d", op.name, cnt+1)
			}
			usedNames[op.name]++
			params = append(params, fmt.Sprintf("%s *%s", op.name, op.cType))
			outParams = append(outParams, op)
		}
	}

	fmt.Fprintf(b, "func %s(%s) *C.char {\n", m.CName, strings.Join(params, ", "))

	goReceiverType := resolveGoReceiverType(ht)
	fmt.Fprintf(b, "\trecv, ok := loadHandle[%s](int64(%s))\n", goReceiverType, receiverParam)
	fmt.Fprintf(b, "\tif !ok {\n\t\treturn C.CString(\"invalid %s handle\")\n\t}\n", strings.ToLower(ht.GoName))

	var goArgs []string
	if m.HasContext {
		goArgs = append(goArgs, "context.Background()")
	}
	for _, p := range m.Params {
		goArgs = append(goArgs, convertParamCToGo(p))
	}

	var resultVars []string
	hasError := false
	for _, r := range m.Returns {
		if r.IsError {
			hasError = true
			resultVars = append(resultVars, "err")
			continue
		}
		resultVars = append(resultVars, fmt.Sprintf("r%d", len(resultVars)))
	}

	if len(resultVars) == 1 && hasError {
		fmt.Fprintf(b, "\treturn toCError(recv.%s(%s))\n", m.GoName, strings.Join(goArgs, ", "))
		b.WriteString("}\n\n")
		return
	}

	if len(resultVars) > 0 {
		fmt.Fprintf(b, "\t%s := recv.%s(%s)\n", strings.Join(resultVars, ", "), m.GoName, strings.Join(goArgs, ", "))
	} else {
		fmt.Fprintf(b, "\trecv.%s(%s)\n", m.GoName, strings.Join(goArgs, ", "))
	}

	if hasError {
		b.WriteString("\tif err != nil {\n\t\treturn toCError(err)\n\t}\n")
	}

	outIdx := 0
	for i, r := range m.Returns {
		if r.IsError {
			continue
		}
		rVar := fmt.Sprintf("r%d", i)
		writeReturnConversion(b, r, rVar, outParams, &outIdx)
		outIdx++
	}

	b.WriteString("\treturn nil\n}\n\n")
}

type outParam struct {
	name  string
	cType string
}

func outParamsForReturn(r Return, idx int) []outParam {
	switch r.Mapping.Kind {
	case MappingReference:
		return []outParam{
			{name: "refNameOut", cType: "*C.char"},
			{name: "hashOut", cType: "*C.char"},
		}
	case MappingHandle:
		return []outParam{{name: "handleOut", cType: "C.longlong"}}
	case MappingIterator:
		return []outParam{{name: "iterOut", cType: "C.longlong"}}
	case MappingString, MappingReferenceName, MappingHash:
		names := []string{"refNameOut", "hashOut", "msgOut", "nameOut", "emailOut"}
		if idx < len(names) {
			return []outParam{{name: names[idx], cType: "*C.char"}}
		}
		return []outParam{{name: fmt.Sprintf("out%d", idx), cType: "*C.char"}}
	case MappingPrimitive:
		if r.CType == "C.longlong" {
			return []outParam{{name: fmt.Sprintf("out%d", idx), cType: "C.longlong"}}
		}
		return []outParam{{name: fmt.Sprintf("out%d", idx), cType: "C.int"}}
	case MappingBool:
		return []outParam{{name: fmt.Sprintf("out%d", idx), cType: "C.int"}}
	case MappingTime, MappingDuration:
		return []outParam{{name: fmt.Sprintf("out%d", idx), cType: "C.longlong"}}
	case MappingStringSlice:
		return []outParam{{name: fmt.Sprintf("out%d", idx), cType: "*C.char"}}
	default:
		return []outParam{{name: fmt.Sprintf("out%d", idx), cType: "*C.char"}}
	}
}

func resolveGoTypeFromMapping(m TypeMapping) string {
	if m.QualifiedName == "" {
		return m.GoType
	}
	qname := m.QualifiedName
	isPtr := false
	lastDot := strings.LastIndex(qname, ".")
	if lastDot < 0 {
		return m.GoType
	}
	pkgPath := qname[:lastDot]
	typeName := qname[lastDot+1:]
	if strings.HasPrefix(typeName, "*") {
		isPtr = true
		typeName = typeName[1:]
	}
	alias := importAlias(pkgPath)
	result := alias + "." + typeName
	if isPtr {
		return "*" + result
	}
	return result
}

func convertParamCToGo(p Param) string {
	switch p.Mapping.Kind {
	case MappingString:
		return fmt.Sprintf("C.GoString(%s)", p.CName)
	case MappingReferenceName:
		return fmt.Sprintf("plumbing.ReferenceName(C.GoString(%s))", p.CName)
	case MappingRevision:
		return fmt.Sprintf("plumbing.Revision(C.GoString(%s))", p.CName)
	case MappingBool:
		return fmt.Sprintf("%s != 0", p.CName)
	case MappingHash:
		return fmt.Sprintf("plumbing.NewHash(C.GoString(%s))", p.CName)
	case MappingOptions:
		goType := resolveGoTypeFromMapping(p.Mapping)
		if p.IsOptional {
			return fmt.Sprintf("func() %s { if int64(%s) == 0 { return nil }; v, _ := loadHandle[%s](int64(%s)); return v }()", goType, p.CName, goType, p.CName)
		}
		return fmt.Sprintf("func() %s { v, _ := loadHandle[%s](int64(%s)); return v }()", goType, goType, p.CName)
	case MappingHandle:
		goType := resolveGoTypeFromMapping(p.Mapping)
		return fmt.Sprintf("func() %s { v, _ := loadHandle[%s](int64(%s)); return v }()", goType, goType, p.CName)
	case MappingPrimitive:
		switch p.Mapping.GoType {
		case "int64":
			return fmt.Sprintf("int64(%s)", p.CName)
		case "uint", "uint32":
			return fmt.Sprintf("%s(%s)", p.Mapping.GoType, p.CName)
		default:
			return fmt.Sprintf("int(%s)", p.CName)
		}
	case MappingEnum:
		return fmt.Sprintf("%s(%s)", resolveEnumCast(p.Mapping), p.CName)
	case MappingTime:
		return fmt.Sprintf("time.Unix(int64(%s), 0)", p.CName)
	case MappingDuration:
		return fmt.Sprintf("time.Duration(int64(%s))", p.CName)
	case MappingStringSlice:
		return fmt.Sprintf("func() []string { var ss []string; _ = json.Unmarshal([]byte(C.GoString(%s)), &ss); return ss }()", p.CName)
	default:
		return p.CName
	}
}

func writeReturnConversion(b *strings.Builder, r Return, rVar string, outParams []outParam, outIdx *int) {
	outName := outParams[*outIdx].name
	switch r.Mapping.Kind {
	case MappingReference:
		fmt.Fprintf(b, "\t*%s = C.CString(string(%s.Name()))\n", outParams[*outIdx].name, rVar)
		fmt.Fprintf(b, "\t*%s = C.CString(%s.Hash().String())\n", outParams[*outIdx+1].name, rVar)
		*outIdx++
	case MappingHandle:
		fmt.Fprintf(b, "\t*%s = C.longlong(storeHandle(%s))\n", outName, rVar)
	case MappingIterator:
		fmt.Fprintf(b, "\t*%s = C.longlong(storeHandle(%s))\n", outName, rVar)
	case MappingString:
		fmt.Fprintf(b, "\t*%s = C.CString(%s)\n", outName, rVar)
	case MappingHash:
		fmt.Fprintf(b, "\t*%s = C.CString(%s.String())\n", outName, rVar)
	case MappingReferenceName:
		fmt.Fprintf(b, "\t*%s = C.CString(string(%s))\n", outName, rVar)
	case MappingPrimitive:
		if r.CType == "C.longlong" {
			fmt.Fprintf(b, "\t*%s = C.longlong(%s)\n", outName, rVar)
		} else {
			fmt.Fprintf(b, "\t*%s = C.int(%s)\n", outName, rVar)
		}
	case MappingBool:
		fmt.Fprintf(b, "\tif %s {\n\t\t*%s = 1\n\t} else {\n\t\t*%s = 0\n\t}\n", rVar, outName, outName)
	case MappingTime:
		fmt.Fprintf(b, "\t*%s = C.longlong(%s.Unix())\n", outName, rVar)
	case MappingDuration:
		fmt.Fprintf(b, "\t*%s = C.longlong(%s)\n", outName, rVar)
	case MappingStringSlice:
		fmt.Fprintf(b, "\t{ d, _ := json.Marshal(%s); *%s = C.CString(string(d)) }\n", rVar, outName)
	}
}

func resolveGoReceiverType(ht *HandleType) string {
	prefix := importAlias(ht.ImportPath) + "."
	if ht.IsPointer {
		return "*" + prefix + ht.GoName
	}
	return prefix + ht.GoName
}

func importAlias(pkgPath string) string {
	switch pkgPath {
	case "github.com/go-git/go-git/v6":
		return "git"
	case "github.com/go-git/go-git/v6/plumbing":
		return "plumbing"
	case "github.com/go-git/go-git/v6/plumbing/object":
		return "object"
	case "github.com/go-git/go-git/v6/plumbing/storer":
		return "storer"
	case "github.com/go-git/go-git/v6/plumbing/transport":
		return "transport"
	case "github.com/go-git/go-git/v6/config":
		return "config"
	case "github.com/ProtonMail/go-crypto/openpgp":
		return "openpgp"
	default:
		parts := strings.Split(pkgPath, "/")
		return parts[len(parts)-1]
	}
}

func generateHandleFree(b *strings.Builder, ht *HandleType) {
	freeName := ht.CPrefix + "Free"
	handleParam := strings.ToLower(ht.GoName[:1]) + "Handle"
	fmt.Fprintf(b, "//export %s\n", freeName)
	fmt.Fprintf(b, "func %s(%s C.longlong) {\n", freeName, handleParam)
	fmt.Fprintf(b, "\tremoveHandle(int64(%s))\n", handleParam)
	fmt.Fprintf(b, "}\n\n")
}

func writeSuppressImports(b *strings.Builder, ht *HandleType, imports []string) {
	b.WriteString("var (\n")
	b.WriteString("\t_ = json.Marshal\n")

	suppressed := map[string]string{
		"memory":    "\t_ = memory.NewStorage\n",
		"memfs":     "\t_ = memfs.New\n",
		"billy":     "\t_ billy.Filesystem\n",
		"config":    "\t_ config.RemoteConfig\n",
		"transport": "\t_ transport.AuthMethod\n",
		"context":   "\t_ = context.Background\n",
		"plumbing":  "\t_ plumbing.Hash\n",
		"object":    "\t_ object.Signature\n",
		"storer":    "\t_ storer.ReferenceIter\n",
		"time":      "\t_ = time.Now\n",
	}

	for _, imp := range imports {
		alias := extractImportAlias(imp)
		if s, ok := suppressed[alias]; ok {
			b.WriteString(s)
		}
	}
	b.WriteString(")\n")
}

func extractImportAlias(imp string) string {
	if strings.Contains(imp, " \"") {
		return strings.SplitN(imp, " ", 2)[0]
	}
	path := strings.Trim(imp, "\"")
	return importAlias(path)
}
