package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const csGenHeader = "// Code generated by gogit-interop/generate. DO NOT EDIT.\n"

func generateCSharp(pkg *Package, outputDir string) error {
	for _, dir := range []string{
		outputDir,
		filepath.Join(outputDir, "Options"),
		filepath.Join(outputDir, "Iterators"),
		filepath.Join(outputDir, "Models"),
	} {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
	}

	if err := generateNativeMethods(pkg, outputDir); err != nil {
		return fmt.Errorf("generating NativeMethods.cs: %w", err)
	}
	if err := generateCSharpWrappers(pkg, outputDir); err != nil {
		return fmt.Errorf("generating wrapper classes: %w", err)
	}
	if err := generateCSharpAuth(outputDir); err != nil {
		return fmt.Errorf("generating Auth.cs: %w", err)
	}
	if err := generateCSharpSigner(outputDir); err != nil {
		return fmt.Errorf("generating Signer.cs: %w", err)
	}
	if err := generateCSharpOptions(pkg, outputDir); err != nil {
		return fmt.Errorf("generating Options: %w", err)
	}
	if err := generateCSharpIterators(outputDir); err != nil {
		return fmt.Errorf("generating Iterators: %w", err)
	}
	if err := generateCSharpModels(outputDir); err != nil {
		return fmt.Errorf("generating Models: %w", err)
	}
	return nil
}

func generateNativeMethods(pkg *Package, dir string) error {
	var b strings.Builder
	b.WriteString(csGenHeader)
	b.WriteString(`#nullable enable
using System.Runtime.InteropServices;

namespace GoGit.Interop;

internal static partial class NativeMethods
{
    private const string LibName = "libgogit";

    // Memory management

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void GitFreeString(IntPtr s);

    public static string? ConsumeGoString(IntPtr ptr)
    {
        if (ptr == IntPtr.Zero)
            return null;

        var str = Marshal.PtrToStringUTF8(ptr);
        GitFreeString(ptr);
        return str;
    }

    public static void ThrowIfError(IntPtr errPtr)
    {
        if (errPtr == IntPtr.Zero)
            return;

        var msg = Marshal.PtrToStringUTF8(errPtr);
        GitFreeString(errPtr);
        throw new GoGitException(msg ?? "unknown error");
    }

    // Repository top-level functions

`)

	generateTopLevelNativeMethods(&b, pkg)
	nativeMethodsHandleSection(&b, pkg)
	nativeMethodsAuthSection(&b)
	nativeMethodsIteratorSection(&b)
	nativeMethodsOptionsSection(&b, pkg)

	b.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, "NativeMethods.cs"), []byte(b.String()), 0644)
}

func generateTopLevelNativeMethods(b *strings.Builder, pkg *Package) {
	for _, fn := range pkg.Functions {
		var params []string
		for _, p := range fn.Params {
			params = append(params, csNativeParam(p))
		}
		for _, r := range fn.Returns {
			if r.IsError {
				continue
			}
			switch r.Mapping.Kind {
			case MappingHandle:
				params = append(params, "out long handleOut")
			case MappingString, MappingReferenceName, MappingHash:
				params = append(params, "out IntPtr strOut")
			}
		}

		b.WriteString("    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]\n")
		fmt.Fprintf(b, "    public static extern IntPtr %s(\n        %s);\n\n", fn.CName, strings.Join(params, ",\n        "))
	}
}
