/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/go-git/go-git/v6/cmd/shared */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "auth_gen.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 3 "errors.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 3 "iterators_gen.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 3 "options_gen.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 3 "remote_gen.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 3 "repository_gen.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 3 "signing_gen.go"

#include <stdlib.h>
#include "callbacks.h"

#line 1 "cgo-generated-wrapper"

#line 3 "submodule_gen.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"

#line 3 "worktree_gen.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* GitAuthNewBasicHTTP(char* username, char* password, long long* handleOut);
extern char* GitAuthNewTokenHTTP(char* token, long long* handleOut);
extern char* GitAuthNewSSHKeyFromFile(char* user, char* pemFile, char* password, long long* handleOut);
extern char* GitAuthNewSSHKey(char* user, char* pem, char* password, long long* handleOut);
extern char* GitAuthNewSSHAgent(char* user, long long* handleOut);
extern char* GitAuthNewSSHPassword(char* user, char* password, long long* handleOut);
extern void GitAuthFree(long long handle);
extern void GitFreeString(char* s);
extern char* GitCommitIterNext(long long iterHandle, char** hashOut, char** msgOut, char** authorNameOut, char** authorEmailOut, long long* tsOut, int* eofOut);
extern void GitCommitIterFree(long long iterHandle);
extern char* GitReferenceIterNext(long long iterHandle, char** refNameOut, char** hashOut, int* eofOut);
extern void GitReferenceIterFree(long long iterHandle);
extern void GitCloneOptionsNew(long long* handleOut);
extern char* GitCloneOptionsSetURL(long long handle, char* val);
extern char* GitCloneOptionsSetAuth(long long handle, long long authHandle);
extern char* GitCloneOptionsSetRemoteName(long long handle, char* val);
extern char* GitCloneOptionsSetReferenceName(long long handle, char* val);
extern char* GitCloneOptionsSetSingleBranch(long long handle, int val);
extern char* GitCloneOptionsSetMirror(long long handle, int val);
extern char* GitCloneOptionsSetNoCheckout(long long handle, int val);
extern char* GitCloneOptionsSetDepth(long long handle, int val);
extern char* GitCloneOptionsSetBare(long long handle, int val);
extern char* GitCloneOptionsSetInsecureSkipTLS(long long handle, int val);
extern char* GitCloneOptionsSetShared(long long handle, int val);
extern char* GitCloneOptionsSetTags(long long handle, int val);
extern void GitCloneOptionsFree(long long handle);
extern void GitPullOptionsNew(long long* handleOut);
extern char* GitPullOptionsSetRemoteName(long long handle, char* val);
extern char* GitPullOptionsSetRemoteURL(long long handle, char* val);
extern char* GitPullOptionsSetReferenceName(long long handle, char* val);
extern char* GitPullOptionsSetSingleBranch(long long handle, int val);
extern char* GitPullOptionsSetDepth(long long handle, int val);
extern char* GitPullOptionsSetAuth(long long handle, long long authHandle);
extern char* GitPullOptionsSetForce(long long handle, int val);
extern char* GitPullOptionsSetInsecureSkipTLS(long long handle, int val);
extern void GitPullOptionsFree(long long handle);
extern void GitFetchOptionsNew(long long* handleOut);
extern char* GitFetchOptionsSetRemoteName(long long handle, char* val);
extern char* GitFetchOptionsSetRemoteURL(long long handle, char* val);
extern char* GitFetchOptionsSetDepth(long long handle, int val);
extern char* GitFetchOptionsSetAuth(long long handle, long long authHandle);
extern char* GitFetchOptionsSetTags(long long handle, int val);
extern char* GitFetchOptionsSetForce(long long handle, int val);
extern char* GitFetchOptionsSetInsecureSkipTLS(long long handle, int val);
extern char* GitFetchOptionsSetPrune(long long handle, int val);
extern void GitFetchOptionsFree(long long handle);
extern void GitPushOptionsNew(long long* handleOut);
extern char* GitPushOptionsSetRemoteName(long long handle, char* val);
extern char* GitPushOptionsSetRemoteURL(long long handle, char* val);
extern char* GitPushOptionsSetAuth(long long handle, long long authHandle);
extern char* GitPushOptionsSetPrune(long long handle, int val);
extern char* GitPushOptionsSetForce(long long handle, int val);
extern char* GitPushOptionsSetInsecureSkipTLS(long long handle, int val);
extern char* GitPushOptionsSetFollowTags(long long handle, int val);
extern char* GitPushOptionsSetAtomic(long long handle, int val);
extern char* GitPushOptionsSetQuiet(long long handle, int val);
extern void GitPushOptionsFree(long long handle);
extern void GitCheckoutOptionsNew(long long* handleOut);
extern char* GitCheckoutOptionsSetHash(long long handle, char* val);
extern char* GitCheckoutOptionsSetBranch(long long handle, char* val);
extern char* GitCheckoutOptionsSetCreate(long long handle, int val);
extern char* GitCheckoutOptionsSetForce(long long handle, int val);
extern char* GitCheckoutOptionsSetKeep(long long handle, int val);
extern void GitCheckoutOptionsFree(long long handle);
extern void GitResetOptionsNew(long long* handleOut);
extern char* GitResetOptionsSetCommit(long long handle, char* val);
extern char* GitResetOptionsSetMode(long long handle, int val);
extern void GitResetOptionsFree(long long handle);
extern void GitRestoreOptionsNew(long long* handleOut);
extern char* GitRestoreOptionsSetStaged(long long handle, int val);
extern char* GitRestoreOptionsSetWorktree(long long handle, int val);
extern char* GitRestoreOptionsAddFile(long long handle, char* path);
extern void GitRestoreOptionsFree(long long handle);
extern void GitCommitOptionsNew(long long* handleOut);
extern char* GitCommitOptionsSetAll(long long handle, int val);
extern char* GitCommitOptionsSetAllowEmptyCommits(long long handle, int val);
extern char* GitCommitOptionsSetSigner(long long handle, long long signerHandle);
extern char* GitCommitOptionsSetAmend(long long handle, int val);
extern char* GitCommitOptionsSetAuthorNameEmail(long long handle, char* name, char* email);
extern char* GitCommitOptionsSetCommitterNameEmail(long long handle, char* name, char* email);
extern void GitCommitOptionsFree(long long handle);
extern void GitCreateTagOptionsNew(long long* handleOut);
extern char* GitCreateTagOptionsSetMessage(long long handle, char* val);
extern char* GitCreateTagOptionsSetTaggerNameEmail(long long handle, char* name, char* email);
extern void GitCreateTagOptionsFree(long long handle);
extern void GitAddOptionsNew(long long* handleOut);
extern char* GitAddOptionsSetAll(long long handle, int val);
extern char* GitAddOptionsSetPath(long long handle, char* val);
extern char* GitAddOptionsSetGlob(long long handle, char* val);
extern char* GitAddOptionsSetSkipStatus(long long handle, int val);
extern void GitAddOptionsFree(long long handle);
extern void GitCleanOptionsNew(long long* handleOut);
extern char* GitCleanOptionsSetDir(long long handle, int val);
extern void GitCleanOptionsFree(long long handle);
extern void GitLogOptionsNew(long long* handleOut);
extern char* GitLogOptionsSetFrom(long long handle, char* val);
extern char* GitLogOptionsSetTo(long long handle, char* val);
extern char* GitLogOptionsSetOrder(long long handle, int val);
extern char* GitLogOptionsSetAll(long long handle, int val);
extern void GitLogOptionsFree(long long handle);
extern void GitPlainOpenOptionsNew(long long* handleOut);
extern char* GitPlainOpenOptionsSetDetectDotGit(long long handle, int val);
extern void GitPlainOpenOptionsFree(long long handle);
extern void GitListOptionsNew(long long* handleOut);
extern char* GitListOptionsSetAuth(long long handle, long long authHandle);
extern char* GitListOptionsSetInsecureSkipTLS(long long handle, int val);
extern char* GitListOptionsSetTimeout(long long handle, int val);
extern void GitListOptionsFree(long long handle);
extern void GitMergeOptionsNew(long long* handleOut);
extern char* GitMergeOptionsSetStrategy(long long handle, int val);
extern void GitMergeOptionsFree(long long handle);
extern void GitSubmoduleUpdateOptionsNew(long long* handleOut);
extern char* GitSubmoduleUpdateOptionsSetInit(long long handle, int val);
extern char* GitSubmoduleUpdateOptionsSetNoFetch(long long handle, int val);
extern char* GitSubmoduleUpdateOptionsSetAuth(long long handle, long long authHandle);
extern char* GitSubmoduleUpdateOptionsSetDepth(long long handle, int val);
extern void GitSubmoduleUpdateOptionsFree(long long handle);
extern char* GitRemoteFetch(long long remoteHandle, long long optsHandle);
extern char* GitRemotePush(long long remoteHandle, long long optsHandle);
extern char* GitRemoteList(long long remoteHandle, long long optsHandle, char** jsonOut);
extern char* GitRemoteConfigName(long long remoteHandle, char** nameOut);
extern void GitRemoteFree(long long remoteHandle);
extern char* GitPlainInit(char* path, int isBare, long long* handleOut);
extern char* GitPlainOpen(char* path, long long* handleOut);
extern char* GitPlainOpenWithOptions(char* path, long long optsHandle, long long* handleOut);
extern char* GitPlainClone(char* path, long long optsHandle, long long* handleOut);
extern char* GitRepositoryHead(long long repoHandle, char** refNameOut, char** hashOut);
extern char* GitRepositoryWorktree(long long repoHandle, long long* wtHandleOut);
extern char* GitRepositoryFetch(long long repoHandle, long long optsHandle);
extern char* GitRepositoryPush(long long repoHandle, long long optsHandle);
extern char* GitRepositoryLog(long long repoHandle, long long optsHandle, long long* iterOut);
extern char* GitRepositoryTags(long long repoHandle, long long* iterOut);
extern char* GitRepositoryBranches(long long repoHandle, long long* iterOut);
extern char* GitRepositoryNotes(long long repoHandle, long long* iterOut);
extern char* GitRepositoryReferences(long long repoHandle, long long* iterOut);
extern char* GitRepositoryReference(long long repoHandle, char* name, int resolved, char** refNameOut, char** hashOut);
extern char* GitRepositoryResolveRevision(long long repoHandle, char* rev, char** hashOut);
extern char* GitRepositoryCreateRemote(long long repoHandle, char* name, char* url, long long* handleOut);
extern char* GitRepositoryRemote(long long repoHandle, char* name, long long* handleOut);
extern char* GitRepositoryDeleteRemote(long long repoHandle, char* name);
extern char* GitRepositoryCreateBranch(long long repoHandle, char* name, char* hash);
extern char* GitRepositoryDeleteBranch(long long repoHandle, char* name);
extern char* GitRepositoryCreateTag(long long repoHandle, char* name, char* hash, long long optsHandle, char** refNameOut, char** hashOut);
extern char* GitRepositoryTag(long long repoHandle, char* name, char** refNameOut, char** hashOut);
extern char* GitRepositoryDeleteTag(long long repoHandle, char* name);
extern char* GitRepositoryCommitObject(long long repoHandle, char* hash, char** commitHashOut, char** msgOut, char** authorNameOut, char** authorEmailOut, long long* tsOut);
extern char* GitRepositoryMerge(long long repoHandle, char* refName, char* hash, long long optsHandle);
extern char* GitRepositoryRemotes(long long repoHandle, char** jsonOut);
extern void GitRepositoryFree(long long repoHandle);
extern char* GitSignerNewPGP(char* armoredKey, char* passphrase, long long* handleOut);
extern char* GitSignerNewCallback(GitSignFunc fn, void* userData, long long* handleOut);
extern char* GitSigningKeyNewPGP(char* armoredKey, char* passphrase, long long* handleOut);
extern void GitSignerFree(long long handle);
extern void GitSigningKeyFree(long long handle);
extern char* GitSubmoduleInit(long long subHandle);
extern char* GitSubmoduleUpdate(long long subHandle, long long optsHandle);
extern char* GitSubmoduleRepository(long long subHandle, long long* handleOut);
extern char* GitSubmoduleConfigName(long long subHandle, char** nameOut);
extern void GitSubmoduleFree(long long subHandle);
extern char* GitWorktreeStatus(long long wtHandle, char** jsonOut);
extern char* GitWorktreeAdd(long long wtHandle, char* path, char** hashOut);
extern char* GitWorktreeAddWithOptions(long long wtHandle, long long optsHandle);
extern char* GitWorktreeAddGlob(long long wtHandle, char* pattern);
extern char* GitWorktreeCommit(long long wtHandle, char* msg, long long optsHandle, char** hashOut);
extern char* GitWorktreeCheckout(long long wtHandle, long long optsHandle);
extern char* GitWorktreePull(long long wtHandle, long long optsHandle);
extern char* GitWorktreeReset(long long wtHandle, long long optsHandle);
extern char* GitWorktreeRestore(long long wtHandle, long long optsHandle);
extern char* GitWorktreeClean(long long wtHandle, long long optsHandle);
extern char* GitWorktreeMove(long long wtHandle, char* fromPath, char* toPath, char** hashOut);
extern char* GitWorktreeSubmodule(long long wtHandle, char* name, long long* handleOut);
extern char* GitWorktreeSubmodules(long long wtHandle, char** jsonOut);
extern void GitWorktreeFree(long long wtHandle);

#ifdef __cplusplus
}
#endif
