// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

/// <summary>Options for a go-git <c>CleanOptions</c> operation. Use the fluent <c>Set*</c> methods to configure, then pass to the corresponding repository method.</summary>
public sealed class CleanOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    /// <summary>Initialises a new <see cref="CleanOptions"/> with default values.</summary>
    public CleanOptions()
    {
        NativeMethods.GitCleanOptionsNew(out _handle);
    }

    /// <summary>Sets the <c>Dir</c> option.</summary>
    public CleanOptions SetDir(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCleanOptionsSetDir(_handle, value ? 1 : 0));
        return this;
    }

    /// <summary>Releases the underlying go-git options object.</summary>
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitCleanOptionsFree(_handle);
        _handle = 0;
    }
}
