// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class CloneOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public CloneOptions()
    {
        NativeMethods.GitCloneOptionsNew(out _handle);
    }

    public CloneOptions SetURL(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetURL(_handle, value));
        return this;
    }

    public CloneOptions SetAuth(Auth value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetAuth(_handle, value.Handle));
        return this;
    }

    public CloneOptions SetRemoteName(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetRemoteName(_handle, value));
        return this;
    }

    public CloneOptions SetReferenceName(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetReferenceName(_handle, value));
        return this;
    }

    public CloneOptions SetSingleBranch(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetSingleBranch(_handle, value ? 1 : 0));
        return this;
    }

    public CloneOptions SetMirror(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetMirror(_handle, value ? 1 : 0));
        return this;
    }

    public CloneOptions SetNoCheckout(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetNoCheckout(_handle, value ? 1 : 0));
        return this;
    }

    public CloneOptions SetDepth(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetDepth(_handle, value));
        return this;
    }

    public CloneOptions SetRecurseSubmodules(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetRecurseSubmodules(_handle, value));
        return this;
    }

    public CloneOptions SetShallowSubmodules(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetShallowSubmodules(_handle, value ? 1 : 0));
        return this;
    }

    public CloneOptions SetTags(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetTags(_handle, value));
        return this;
    }

    public CloneOptions SetInsecureSkipTLS(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetInsecureSkipTLS(_handle, value ? 1 : 0));
        return this;
    }

    public CloneOptions SetShared(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetShared(_handle, value ? 1 : 0));
        return this;
    }

    public CloneOptions SetBare(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetBare(_handle, value ? 1 : 0));
        return this;
    }

    public CloneOptions SetProxy(string url, string? username = null, string? password = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCloneOptionsSetProxy(_handle, url, username ?? "", password ?? ""));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitCloneOptionsFree(_handle);
        _handle = 0;
    }
}
