// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

/// <summary>Options for a go-git <c>CommitOptions</c> operation. Use the fluent <c>Set*</c> methods to configure, then pass to the corresponding repository method.</summary>
public sealed class CommitOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    /// <summary>Initialises a new <see cref="CommitOptions"/> with default values.</summary>
    public CommitOptions()
    {
        NativeMethods.GitCommitOptionsNew(out _handle);
    }

    /// <summary>Sets the <c>All</c> option.</summary>
    public CommitOptions SetAll(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitOptionsSetAll(_handle, value ? 1 : 0));
        return this;
    }

    /// <summary>Sets the <c>AllowEmptyCommits</c> option.</summary>
    public CommitOptions SetAllowEmptyCommits(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitOptionsSetAllowEmptyCommits(_handle, value ? 1 : 0));
        return this;
    }

    /// <summary>Sets the <c>Signer</c> option.</summary>
    public CommitOptions SetSigner(Signer value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitOptionsSetSigner(_handle, value.Handle));
        return this;
    }

    /// <summary>Sets the <c>Amend</c> option.</summary>
    public CommitOptions SetAmend(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitOptionsSetAmend(_handle, value ? 1 : 0));
        return this;
    }

    /// <summary>Sets the <c>Author</c> option.</summary>
    public CommitOptions SetAuthor(string name, string email)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitOptionsSetAuthorNameEmail(_handle, name, email));
        return this;
    }

    /// <summary>Sets the <c>Committer</c> option.</summary>
    public CommitOptions SetCommitter(string name, string email)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitOptionsSetCommitterNameEmail(_handle, name, email));
        return this;
    }

    /// <summary>Sets the <c>Parents</c> option.</summary>
    public CommitOptions SetParents(params string[] hashes)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCommitOptionsSetParents(_handle, System.Text.Json.JsonSerializer.Serialize(hashes)));
        return this;
    }

    /// <summary>Releases the underlying go-git options object.</summary>
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitCommitOptionsFree(_handle);
        _handle = 0;
    }
}
