// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class CreateTagOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public CreateTagOptions()
    {
        NativeMethods.GitCreateTagOptionsNew(out _handle);
    }

    public CreateTagOptions SetMessage(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCreateTagOptionsSetMessage(_handle, value));
        return this;
    }

    public CreateTagOptions SetTagger(string name, string email)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCreateTagOptionsSetTaggerNameEmail(_handle, name, email));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitCreateTagOptionsFree(_handle);
        _handle = 0;
    }
}
