// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class DiffTreeOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public DiffTreeOptions()
    {
        NativeMethods.GitDiffTreeOptionsNew(out _handle);
    }

    public DiffTreeOptions SetDetectRenames(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitDiffTreeOptionsSetDetectRenames(_handle, value ? 1 : 0));
        return this;
    }

    public DiffTreeOptions SetRenameScore(uint value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitDiffTreeOptionsSetRenameScore(_handle, value));
        return this;
    }

    public DiffTreeOptions SetRenameLimit(uint value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitDiffTreeOptionsSetRenameLimit(_handle, value));
        return this;
    }

    public DiffTreeOptions SetOnlyExactRenames(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitDiffTreeOptionsSetOnlyExactRenames(_handle, value ? 1 : 0));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitDiffTreeOptionsFree(_handle);
        _handle = 0;
    }
}
