// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class GrepOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public GrepOptions()
    {
        NativeMethods.GitGrepOptionsNew(out _handle);
    }

    public GrepOptions SetInvertMatch(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitGrepOptionsSetInvertMatch(_handle, value ? 1 : 0));
        return this;
    }

    public GrepOptions SetCommitHash(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitGrepOptionsSetCommitHash(_handle, value));
        return this;
    }

    public GrepOptions SetReferenceName(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitGrepOptionsSetReferenceName(_handle, value));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitGrepOptionsFree(_handle);
        _handle = 0;
    }
}
