// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

/// <summary>Options for a go-git <c>GrepOptions</c> operation. Use the fluent <c>Set*</c> methods to configure, then pass to the corresponding repository method.</summary>
public sealed class GrepOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    /// <summary>Initialises a new <see cref="GrepOptions"/> with default values.</summary>
    public GrepOptions()
    {
        NativeMethods.GitGrepOptionsNew(out _handle);
    }

    /// <summary>Sets the <c>InvertMatch</c> option.</summary>
    public GrepOptions SetInvertMatch(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitGrepOptionsSetInvertMatch(_handle, value ? 1 : 0));
        return this;
    }

    /// <summary>Sets the <c>CommitHash</c> option.</summary>
    public GrepOptions SetCommitHash(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitGrepOptionsSetCommitHash(_handle, value));
        return this;
    }

    /// <summary>Sets the <c>ReferenceName</c> option.</summary>
    public GrepOptions SetReferenceName(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitGrepOptionsSetReferenceName(_handle, value));
        return this;
    }

    /// <summary>Releases the underlying go-git options object.</summary>
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitGrepOptionsFree(_handle);
        _handle = 0;
    }
}
