// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class ListOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public ListOptions()
    {
        NativeMethods.GitListOptionsNew(out _handle);
    }

    public ListOptions SetAuth(Auth value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitListOptionsSetAuth(_handle, value.Handle));
        return this;
    }

    public ListOptions SetInsecureSkipTLS(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitListOptionsSetInsecureSkipTLS(_handle, value ? 1 : 0));
        return this;
    }

    public ListOptions SetPeelingOption(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitListOptionsSetPeelingOption(_handle, value));
        return this;
    }

    public ListOptions SetTimeout(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitListOptionsSetTimeout(_handle, value));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitListOptionsFree(_handle);
        _handle = 0;
    }
}
