// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class LogLimitOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public LogLimitOptions()
    {
        NativeMethods.GitLogLimitOptionsNew(out _handle);
    }

    public LogLimitOptions SetSince(DateTimeOffset value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogLimitOptionsSetSince(_handle, value.ToUnixTimeSeconds()));
        return this;
    }

    public LogLimitOptions SetUntil(DateTimeOffset value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogLimitOptionsSetUntil(_handle, value.ToUnixTimeSeconds()));
        return this;
    }

    public LogLimitOptions SetTailHash(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogLimitOptionsSetTailHash(_handle, value));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitLogLimitOptionsFree(_handle);
        _handle = 0;
    }
}
