// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

/// <summary>Options for a go-git <c>LogOptions</c> operation. Use the fluent <c>Set*</c> methods to configure, then pass to the corresponding repository method.</summary>
public sealed class LogOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    /// <summary>Initialises a new <see cref="LogOptions"/> with default values.</summary>
    public LogOptions()
    {
        NativeMethods.GitLogOptionsNew(out _handle);
    }

    /// <summary>Sets the <c>From</c> option.</summary>
    public LogOptions SetFrom(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogOptionsSetFrom(_handle, value));
        return this;
    }

    /// <summary>Sets the <c>To</c> option.</summary>
    public LogOptions SetTo(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogOptionsSetTo(_handle, value));
        return this;
    }

    /// <summary>Sets the <c>Order</c> option.</summary>
    public LogOptions SetOrder(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogOptionsSetOrder(_handle, value));
        return this;
    }

    /// <summary>Sets the <c>FileName</c> option.</summary>
    public LogOptions SetFileName(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogOptionsSetFileName(_handle, value));
        return this;
    }

    /// <summary>Sets the <c>All</c> option.</summary>
    public LogOptions SetAll(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogOptionsSetAll(_handle, value ? 1 : 0));
        return this;
    }

    /// <summary>Sets the <c>Since</c> option.</summary>
    public LogOptions SetSince(DateTimeOffset value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogOptionsSetSince(_handle, value.ToUnixTimeSeconds()));
        return this;
    }

    /// <summary>Sets the <c>Until</c> option.</summary>
    public LogOptions SetUntil(DateTimeOffset value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogOptionsSetUntil(_handle, value.ToUnixTimeSeconds()));
        return this;
    }

    /// <summary>Releases the underlying go-git options object.</summary>
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitLogOptionsFree(_handle);
        _handle = 0;
    }
}
