// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class LogOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public LogOptions()
    {
        NativeMethods.GitLogOptionsNew(out _handle);
    }

    public LogOptions SetFrom(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogOptionsSetFrom(_handle, value));
        return this;
    }

    public LogOptions SetTo(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogOptionsSetTo(_handle, value));
        return this;
    }

    public LogOptions SetOrder(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogOptionsSetOrder(_handle, value));
        return this;
    }

    public LogOptions SetFileName(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogOptionsSetFileName(_handle, value));
        return this;
    }

    public LogOptions SetAll(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogOptionsSetAll(_handle, value ? 1 : 0));
        return this;
    }

    public LogOptions SetSince(DateTimeOffset value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogOptionsSetSince(_handle, value.ToUnixTimeSeconds()));
        return this;
    }

    public LogOptions SetUntil(DateTimeOffset value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitLogOptionsSetUntil(_handle, value.ToUnixTimeSeconds()));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitLogOptionsFree(_handle);
        _handle = 0;
    }
}
