// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

/// <summary>Options for a go-git <c>MergeOptions</c> operation. Use the fluent <c>Set*</c> methods to configure, then pass to the corresponding repository method.</summary>
public sealed class MergeOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    /// <summary>Initialises a new <see cref="MergeOptions"/> with default values.</summary>
    public MergeOptions()
    {
        NativeMethods.GitMergeOptionsNew(out _handle);
    }

    /// <summary>Sets the <c>Strategy</c> option.</summary>
    public MergeOptions SetStrategy(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitMergeOptionsSetStrategy(_handle, value));
        return this;
    }

    /// <summary>Releases the underlying go-git options object.</summary>
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitMergeOptionsFree(_handle);
        _handle = 0;
    }
}
