// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class PlainOpenOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public PlainOpenOptions()
    {
        NativeMethods.GitPlainOpenOptionsNew(out _handle);
    }

    public PlainOpenOptions SetDetectDotGit(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitPlainOpenOptionsSetDetectDotGit(_handle, value ? 1 : 0));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitPlainOpenOptionsFree(_handle);
        _handle = 0;
    }
}
