// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class ProxyOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public ProxyOptions()
    {
        NativeMethods.GitProxyOptionsNew(out _handle);
    }

    public ProxyOptions SetURL(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitProxyOptionsSetURL(_handle, value));
        return this;
    }

    public ProxyOptions SetUsername(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitProxyOptionsSetUsername(_handle, value));
        return this;
    }

    public ProxyOptions SetPassword(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitProxyOptionsSetPassword(_handle, value));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitProxyOptionsFree(_handle);
        _handle = 0;
    }
}
