// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class PruneOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public PruneOptions()
    {
        NativeMethods.GitPruneOptionsNew(out _handle);
    }

    public PruneOptions SetOnlyObjectsOlderThan(DateTimeOffset value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitPruneOptionsSetOnlyObjectsOlderThan(_handle, value.ToUnixTimeSeconds()));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitPruneOptionsFree(_handle);
        _handle = 0;
    }
}
