// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class PullOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public PullOptions()
    {
        NativeMethods.GitPullOptionsNew(out _handle);
    }

    public PullOptions SetRemoteName(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitPullOptionsSetRemoteName(_handle, value));
        return this;
    }

    public PullOptions SetRemoteURL(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitPullOptionsSetRemoteURL(_handle, value));
        return this;
    }

    public PullOptions SetReferenceName(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitPullOptionsSetReferenceName(_handle, value));
        return this;
    }

    public PullOptions SetSingleBranch(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitPullOptionsSetSingleBranch(_handle, value ? 1 : 0));
        return this;
    }

    public PullOptions SetDepth(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitPullOptionsSetDepth(_handle, value));
        return this;
    }

    public PullOptions SetAuth(Auth value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitPullOptionsSetAuth(_handle, value.Handle));
        return this;
    }

    public PullOptions SetRecurseSubmodules(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitPullOptionsSetRecurseSubmodules(_handle, value));
        return this;
    }

    public PullOptions SetForce(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitPullOptionsSetForce(_handle, value ? 1 : 0));
        return this;
    }

    public PullOptions SetInsecureSkipTLS(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitPullOptionsSetInsecureSkipTLS(_handle, value ? 1 : 0));
        return this;
    }

    public PullOptions SetProxy(string url, string? username = null, string? password = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitPullOptionsSetProxy(_handle, url, username ?? "", password ?? ""));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitPullOptionsFree(_handle);
        _handle = 0;
    }
}
