// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class ReceivePackOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public ReceivePackOptions()
    {
        NativeMethods.GitReceivePackOptionsNew(out _handle);
    }

    public ReceivePackOptions SetGitProtocol(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitReceivePackOptionsSetGitProtocol(_handle, value));
        return this;
    }

    public ReceivePackOptions SetAdvertiseRefs(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitReceivePackOptionsSetAdvertiseRefs(_handle, value ? 1 : 0));
        return this;
    }

    public ReceivePackOptions SetStatelessRPC(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitReceivePackOptionsSetStatelessRPC(_handle, value ? 1 : 0));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitReceivePackOptionsFree(_handle);
        _handle = 0;
    }
}
