// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class ResetOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public ResetOptions()
    {
        NativeMethods.GitResetOptionsNew(out _handle);
    }

    public ResetOptions SetCommit(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitResetOptionsSetCommit(_handle, value));
        return this;
    }

    public ResetOptions SetMode(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitResetOptionsSetMode(_handle, value));
        return this;
    }

    public ResetOptions SetFiles(string[] value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitResetOptionsSetFiles(_handle, System.Text.Json.JsonSerializer.Serialize(value)));
        return this;
    }

    public ResetOptions SetSparseDirs(string[] value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitResetOptionsSetSparseDirs(_handle, System.Text.Json.JsonSerializer.Serialize(value)));
        return this;
    }

    public ResetOptions SetSkipSparseDirValidation(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitResetOptionsSetSkipSparseDirValidation(_handle, value ? 1 : 0));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitResetOptionsFree(_handle);
        _handle = 0;
    }
}
