// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class StatusOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public StatusOptions()
    {
        NativeMethods.GitStatusOptionsNew(out _handle);
    }

    public StatusOptions SetStrategy(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitStatusOptionsSetStrategy(_handle, value));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitStatusOptionsFree(_handle);
        _handle = 0;
    }
}
