// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class UploadPackOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public UploadPackOptions()
    {
        NativeMethods.GitUploadPackOptionsNew(out _handle);
    }

    public UploadPackOptions SetGitProtocol(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitUploadPackOptionsSetGitProtocol(_handle, value));
        return this;
    }

    public UploadPackOptions SetAdvertiseRefs(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitUploadPackOptionsSetAdvertiseRefs(_handle, value ? 1 : 0));
        return this;
    }

    public UploadPackOptions SetStatelessRPC(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitUploadPackOptionsSetStatelessRPC(_handle, value ? 1 : 0));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitUploadPackOptionsFree(_handle);
        _handle = 0;
    }
}
