// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class BlobIterator : IEnumerable<Blob>, IDisposable
{
    private long _handle;
    private bool _disposed;

    internal BlobIterator(long handle) => _handle = handle;

    public IEnumerator<Blob> GetEnumerator()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        while (true)
        {
            var err = NativeMethods.GitBlobIterNext(
                _handle,
                out var blobHandle, out var eof);
            NativeMethods.ThrowIfError(err);

            if (eof != 0) yield break;

            yield return new Blob(blobHandle);
        }
    }

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitBlobIterFree(_handle);
        _handle = 0;
    }
}
