// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

/// <summary>Lazily iterates over <see cref="ReferenceInfo"/> objects returned by go-git. Must be disposed after use.</summary>
public sealed class ReferenceIterator : IEnumerable<ReferenceInfo>, IDisposable
{
    private long _handle;
    private bool _disposed;

    internal ReferenceIterator(long handle) => _handle = handle;

    public IEnumerator<ReferenceInfo> GetEnumerator()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        while (true)
        {
            var err = NativeMethods.GitReferenceIterNext(
                _handle,
                out var refName, out var hash, out var eof);
            NativeMethods.ThrowIfError(err);

            if (eof != 0) yield break;

            yield return new ReferenceInfo
            {
                Name = NativeMethods.ConsumeGoString(refName)!,
                Hash = NativeMethods.ConsumeGoString(hash)!,
            };
        }
    }

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitReferenceIterFree(_handle);
        _handle = 0;
    }
}
