// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

public sealed class TagIterator : IEnumerable<Tag>, IDisposable
{
    private long _handle;
    private bool _disposed;

    internal TagIterator(long handle) => _handle = handle;

    public IEnumerator<Tag> GetEnumerator()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        while (true)
        {
            var err = NativeMethods.GitTagIterNext(
                _handle,
                out var tagHandle, out var eof);
            NativeMethods.ThrowIfError(err);

            if (eof != 0) yield break;

            yield return new Tag(tagHandle);
        }
    }

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitTagIterFree(_handle);
        _handle = 0;
    }
}
