// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
namespace GoGit.Interop;

/// <summary>Lazily iterates over <see cref="Tree"/> objects returned by go-git. Must be disposed after use.</summary>
public sealed class TreeIterator : IEnumerable<Tree>, IDisposable
{
    private long _handle;
    private bool _disposed;

    internal TreeIterator(long handle) => _handle = handle;

    public IEnumerator<Tree> GetEnumerator()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        while (true)
        {
            var err = NativeMethods.GitTreeIterNext(
                _handle,
                out var treeHandle, out var eof);
            NativeMethods.ThrowIfError(err);

            if (eof != 0) yield break;

            yield return new Tree(treeHandle);
        }
    }

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitTreeIterFree(_handle);
        _handle = 0;
    }
}
