package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

func generateCSharp(pkg *Package, outputDir string) error {
	dotnetDir := filepath.Join(outputDir, "dotnet", "GoGit.Interop")

	for _, dir := range []string{
		dotnetDir,
		filepath.Join(dotnetDir, "Options"),
		filepath.Join(dotnetDir, "Iterators"),
		filepath.Join(dotnetDir, "Models"),
	} {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
	}

	if err := generateNativeMethods(pkg, dotnetDir); err != nil {
		return fmt.Errorf("generating NativeMethods.cs: %w", err)
	}
	if err := generateCSharpRepository(dotnetDir); err != nil {
		return fmt.Errorf("generating Repository.cs: %w", err)
	}
	if err := generateCSharpWorktree(dotnetDir); err != nil {
		return fmt.Errorf("generating Worktree.cs: %w", err)
	}
	if err := generateCSharpRemote(dotnetDir); err != nil {
		return fmt.Errorf("generating Remote.cs: %w", err)
	}
	if err := generateCSharpSubmodule(dotnetDir); err != nil {
		return fmt.Errorf("generating Submodule.cs: %w", err)
	}
	if err := generateCSharpAuth(dotnetDir); err != nil {
		return fmt.Errorf("generating Auth.cs: %w", err)
	}
	if err := generateCSharpSigner(dotnetDir); err != nil {
		return fmt.Errorf("generating Signer.cs: %w", err)
	}
	if err := generateCSharpOptions(pkg, dotnetDir); err != nil {
		return fmt.Errorf("generating Options: %w", err)
	}
	if err := generateCSharpIterators(dotnetDir); err != nil {
		return fmt.Errorf("generating Iterators: %w", err)
	}
	if err := generateCSharpModels(dotnetDir); err != nil {
		return fmt.Errorf("generating Models: %w", err)
	}
	return nil
}

func generateNativeMethods(pkg *Package, dir string) error {
	var b strings.Builder
	b.WriteString(`// <auto-generated/>
#nullable enable
using System.Runtime.InteropServices;

namespace GoGit.Interop;

internal static partial class NativeMethods
{
    private const string LibName = "libgogit";

    // Memory management

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void GitFreeString(IntPtr s);

    public static string? ConsumeGoString(IntPtr ptr)
    {
        if (ptr == IntPtr.Zero)
            return null;

        var str = Marshal.PtrToStringUTF8(ptr);
        GitFreeString(ptr);
        return str;
    }

    public static void ThrowIfError(IntPtr errPtr)
    {
        if (errPtr == IntPtr.Zero)
            return;

        var msg = Marshal.PtrToStringUTF8(errPtr);
        GitFreeString(errPtr);
        throw new GoGitException(msg ?? "unknown error");
    }

    // Repository top-level functions

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitPlainInit(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string path,
        int isBare,
        out long handleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitPlainOpen(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string path,
        out long handleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitPlainOpenWithOptions(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string path,
        long optsHandle,
        out long handleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitPlainClone(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string path,
        long optsHandle,
        out long handleOut);

    // Repository methods

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryHead(long repoHandle, out IntPtr refNameOut, out IntPtr hashOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryWorktree(long repoHandle, out long wtHandleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryFetch(long repoHandle, long optsHandle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryPush(long repoHandle, long optsHandle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryLog(long repoHandle, long optsHandle, out long iterOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryTags(long repoHandle, out long iterOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryBranches(long repoHandle, out long iterOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryNotes(long repoHandle, out long iterOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryReferences(long repoHandle, out long iterOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryReference(
        long repoHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name,
        int resolved,
        out IntPtr refNameOut,
        out IntPtr hashOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryResolveRevision(
        long repoHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string rev,
        out IntPtr hashOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryCreateRemote(
        long repoHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string url,
        out long handleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryRemote(
        long repoHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name,
        out long handleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryDeleteRemote(
        long repoHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryCreateBranch(
        long repoHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string hash);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryDeleteBranch(
        long repoHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryCreateTag(
        long repoHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string hash,
        long optsHandle,
        out IntPtr refNameOut,
        out IntPtr hashOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryTag(
        long repoHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name,
        out IntPtr refNameOut,
        out IntPtr hashOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryDeleteTag(
        long repoHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryCommitObject(
        long repoHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string hash,
        out IntPtr commitHashOut,
        out IntPtr msgOut,
        out IntPtr authorNameOut,
        out IntPtr authorEmailOut,
        out long tsOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryMerge(
        long repoHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string refName,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string hash,
        long optsHandle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRepositoryRemotes(long repoHandle, out IntPtr jsonOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void GitRepositoryFree(long repoHandle);

    // Worktree methods

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitWorktreeStatus(long wtHandle, out IntPtr jsonOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitWorktreeAdd(
        long wtHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string path,
        out IntPtr hashOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitWorktreeAddWithOptions(long wtHandle, long optsHandle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitWorktreeAddGlob(
        long wtHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string pattern);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitWorktreeCommit(
        long wtHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string msg,
        long optsHandle,
        out IntPtr hashOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitWorktreeCheckout(long wtHandle, long optsHandle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitWorktreePull(long wtHandle, long optsHandle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitWorktreeReset(long wtHandle, long optsHandle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitWorktreeRestore(long wtHandle, long optsHandle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitWorktreeClean(long wtHandle, long optsHandle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitWorktreeMove(
        long wtHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string fromPath,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string toPath,
        out IntPtr hashOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitWorktreeSubmodule(
        long wtHandle,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string name,
        out long handleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitWorktreeSubmodules(long wtHandle, out IntPtr jsonOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void GitWorktreeFree(long wtHandle);

    // Remote methods

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRemoteFetch(long remoteHandle, long optsHandle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRemotePush(long remoteHandle, long optsHandle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRemoteList(long remoteHandle, long optsHandle, out IntPtr jsonOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitRemoteConfigName(long remoteHandle, out IntPtr nameOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void GitRemoteFree(long remoteHandle);

    // Submodule methods

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitSubmoduleInit(long subHandle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitSubmoduleUpdate(long subHandle, long optsHandle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitSubmoduleRepository(long subHandle, out long handleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitSubmoduleConfigName(long subHandle, out IntPtr nameOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void GitSubmoduleFree(long subHandle);

    // Auth constructors

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitAuthNewBasicHTTP(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string username,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string password,
        out long handleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitAuthNewTokenHTTP(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string token,
        out long handleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitAuthNewSSHKeyFromFile(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string user,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string pemFile,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string password,
        out long handleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitAuthNewSSHKey(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string user,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string pem,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string password,
        out long handleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitAuthNewSSHAgent(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string user,
        out long handleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitAuthNewSSHPassword(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string user,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string password,
        out long handleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void GitAuthFree(long handle);

    // Signer constructors

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitSignerNewPGP(
        [MarshalAs(UnmanagedType.LPUTF8Str)] string armoredKey,
        [MarshalAs(UnmanagedType.LPUTF8Str)] string passphrase,
        out long handleOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void GitSignerFree(long handle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void GitSigningKeyFree(long handle);

    // Iterators

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitCommitIterNext(
        long iterHandle,
        out IntPtr hashOut,
        out IntPtr msgOut,
        out IntPtr authorNameOut,
        out IntPtr authorEmailOut,
        out long tsOut,
        out int eofOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void GitCommitIterFree(long iterHandle);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr GitReferenceIterNext(
        long iterHandle,
        out IntPtr refNameOut,
        out IntPtr hashOut,
        out int eofOut);

    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
    public static extern void GitReferenceIterFree(long iterHandle);

`)

	// Generate options P/Invoke declarations
	for _, opts := range pkg.Options {
		fmt.Fprintf(&b, "    // %s\n\n", opts.GoName)
		fmt.Fprintf(&b, "    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]\n")
		fmt.Fprintf(&b, "    public static extern void %sNew(out long handleOut);\n\n", opts.CPrefix)

		for _, f := range opts.Fields {
			setterName := opts.CPrefix + "Set" + f.GoName
			fmt.Fprintf(&b, "    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]\n")

			switch f.Mapping.Kind {
			case MappingString, MappingReferenceName, MappingHash:
				fmt.Fprintf(&b, "    public static extern IntPtr %s(long handle, [MarshalAs(UnmanagedType.LPUTF8Str)] string val);\n\n", setterName)
			case MappingBool:
				fmt.Fprintf(&b, "    public static extern IntPtr %s(long handle, int val);\n\n", setterName)
			case MappingPrimitive, MappingEnum:
				fmt.Fprintf(&b, "    public static extern IntPtr %s(long handle, int val);\n\n", setterName)
			case MappingAuth:
				fmt.Fprintf(&b, "    public static extern IntPtr %s(long handle, long authHandle);\n\n", setterName)
			case MappingSigner:
				fmt.Fprintf(&b, "    public static extern IntPtr %s(long handle, long signerHandle);\n\n", setterName)
			}
		}

		// Signature setters
		if opts.GoName == "CommitOptions" {
			for _, sigField := range []string{"Author", "Committer"} {
				fmt.Fprintf(&b, "    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]\n")
				fmt.Fprintf(&b, "    public static extern IntPtr %sSet%sNameEmail(\n", opts.CPrefix, sigField)
				fmt.Fprintf(&b, "        long handle,\n")
				fmt.Fprintf(&b, "        [MarshalAs(UnmanagedType.LPUTF8Str)] string name,\n")
				fmt.Fprintf(&b, "        [MarshalAs(UnmanagedType.LPUTF8Str)] string email);\n\n")
			}
		}
		if opts.GoName == "CreateTagOptions" {
			fmt.Fprintf(&b, "    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]\n")
			fmt.Fprintf(&b, "    public static extern IntPtr %sSetTaggerNameEmail(\n", opts.CPrefix)
			fmt.Fprintf(&b, "        long handle,\n")
			fmt.Fprintf(&b, "        [MarshalAs(UnmanagedType.LPUTF8Str)] string name,\n")
			fmt.Fprintf(&b, "        [MarshalAs(UnmanagedType.LPUTF8Str)] string email);\n\n")
		}
		if opts.GoName == "RestoreOptions" {
			fmt.Fprintf(&b, "    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]\n")
			fmt.Fprintf(&b, "    public static extern IntPtr %sAddFile(long handle, [MarshalAs(UnmanagedType.LPUTF8Str)] string path);\n\n", opts.CPrefix)
		}

		fmt.Fprintf(&b, "    [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]\n")
		fmt.Fprintf(&b, "    public static extern void %sFree(long handle);\n\n", opts.CPrefix)
	}

	b.WriteString("}\n")

	return os.WriteFile(filepath.Join(dir, "NativeMethods.cs"), []byte(b.String()), 0644)
}

func generateCSharpRepository(dir string) error {
	content := `// <auto-generated/>
#nullable enable
using System.Text.Json;

namespace GoGit.Interop;

public sealed class Repository : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Repository(long handle) => _handle = handle;

    public static Repository Init(string path, bool isBare = false)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitPlainInit(path, isBare ? 1 : 0, out var handle));
        return new Repository(handle);
    }

    public static Repository Open(string path)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitPlainOpen(path, out var handle));
        return new Repository(handle);
    }

    public static Repository OpenWithOptions(string path, PlainOpenOptions options)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitPlainOpenWithOptions(path, options.Handle, out var handle));
        return new Repository(handle);
    }

    public static Repository Clone(string path, CloneOptions options)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitPlainClone(path, options.Handle, out var handle));
        return new Repository(handle);
    }

    public (string RefName, string Hash) Head()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryHead(_handle, out var refName, out var hash));
        return (NativeMethods.ConsumeGoString(refName)!, NativeMethods.ConsumeGoString(hash)!);
    }

    public Worktree GetWorktree()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryWorktree(_handle, out var wtHandle));
        return new Worktree(wtHandle);
    }

    public void Fetch(FetchOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryFetch(_handle, options.Handle));
    }

    public void Push(PushOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryPush(_handle, options.Handle));
    }

    public CommitIterator Log(LogOptions? options = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        var optsHandle = options?.Handle ?? 0;
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryLog(_handle, optsHandle, out var iterHandle));
        return new CommitIterator(iterHandle);
    }

    public ReferenceIterator Tags()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryTags(_handle, out var iterHandle));
        return new ReferenceIterator(iterHandle);
    }

    public ReferenceIterator Branches()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryBranches(_handle, out var iterHandle));
        return new ReferenceIterator(iterHandle);
    }

    public ReferenceIterator Notes()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryNotes(_handle, out var iterHandle));
        return new ReferenceIterator(iterHandle);
    }

    public ReferenceIterator References()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryReferences(_handle, out var iterHandle));
        return new ReferenceIterator(iterHandle);
    }

    public (string RefName, string Hash) Reference(string name, bool resolved = true)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryReference(_handle, name, resolved ? 1 : 0, out var refName, out var hash));
        return (NativeMethods.ConsumeGoString(refName)!, NativeMethods.ConsumeGoString(hash)!);
    }

    public string ResolveRevision(string rev)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryResolveRevision(_handle, rev, out var hash));
        return NativeMethods.ConsumeGoString(hash)!;
    }

    public Remote CreateRemote(string name, string url)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCreateRemote(_handle, name, url, out var handle));
        return new Remote(handle);
    }

    public Remote GetRemote(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryRemote(_handle, name, out var handle));
        return new Remote(handle);
    }

    public void DeleteRemote(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryDeleteRemote(_handle, name));
    }

    public string[] Remotes()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryRemotes(_handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<string[]>(json) ?? [];
    }

    public void CreateBranch(string name, string hash)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCreateBranch(_handle, name, hash));
    }

    public void DeleteBranch(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryDeleteBranch(_handle, name));
    }

    public (string RefName, string Hash) CreateTag(string name, string hash, CreateTagOptions? options = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        var optsHandle = options?.Handle ?? 0;
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCreateTag(_handle, name, hash, optsHandle, out var refName, out var hashOut));
        return (NativeMethods.ConsumeGoString(refName)!, NativeMethods.ConsumeGoString(hashOut)!);
    }

    public (string RefName, string Hash) Tag(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryTag(_handle, name, out var refName, out var hash));
        return (NativeMethods.ConsumeGoString(refName)!, NativeMethods.ConsumeGoString(hash)!);
    }

    public void DeleteTag(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryDeleteTag(_handle, name));
    }

    public Commit GetCommitObject(string hash)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryCommitObject(
            _handle, hash,
            out var commitHash, out var msg, out var authorName, out var authorEmail, out var ts));
        return new Commit
        {
            Hash = NativeMethods.ConsumeGoString(commitHash)!,
            Message = NativeMethods.ConsumeGoString(msg)!,
            AuthorName = NativeMethods.ConsumeGoString(authorName)!,
            AuthorEmail = NativeMethods.ConsumeGoString(authorEmail)!,
            AuthorTimestamp = DateTimeOffset.FromUnixTimeSeconds(ts),
        };
    }

    public void Merge(string refName, string hash, MergeOptions? options = null)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        var optsHandle = options?.Handle ?? 0;
        NativeMethods.ThrowIfError(NativeMethods.GitRepositoryMerge(_handle, refName, hash, optsHandle));
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitRepositoryFree(_handle);
        _handle = 0;
    }
}
`
	return os.WriteFile(filepath.Join(dir, "Repository.cs"), []byte(content), 0644)
}

func generateCSharpWorktree(dir string) error {
	content := `// <auto-generated/>
#nullable enable
using System.Text.Json;

namespace GoGit.Interop;

public sealed class Worktree : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Worktree(long handle) => _handle = handle;

    public Dictionary<string, FileStatus> Status()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeStatus(_handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<Dictionary<string, FileStatus>>(json) ?? new();
    }

    public string Add(string path)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeAdd(_handle, path, out var hash));
        return NativeMethods.ConsumeGoString(hash)!;
    }

    public void AddWithOptions(AddOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeAddWithOptions(_handle, options.Handle));
    }

    public void AddGlob(string pattern)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeAddGlob(_handle, pattern));
    }

    public string Commit(string message, CommitOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeCommit(_handle, message, options.Handle, out var hash));
        return NativeMethods.ConsumeGoString(hash)!;
    }

    public void Checkout(CheckoutOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeCheckout(_handle, options.Handle));
    }

    public void Pull(PullOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreePull(_handle, options.Handle));
    }

    public void Reset(ResetOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeReset(_handle, options.Handle));
    }

    public void Restore(RestoreOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeRestore(_handle, options.Handle));
    }

    public void Clean(CleanOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeClean(_handle, options.Handle));
    }

    public string Move(string from, string to)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeMove(_handle, from, to, out var hash));
        return NativeMethods.ConsumeGoString(hash)!;
    }

    public Submodule GetSubmodule(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeSubmodule(_handle, name, out var handle));
        return new Submodule(handle);
    }

    public string[] Submodules()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeSubmodules(_handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<string[]>(json) ?? [];
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitWorktreeFree(_handle);
        _handle = 0;
    }
}
`
	return os.WriteFile(filepath.Join(dir, "Worktree.cs"), []byte(content), 0644)
}

func generateCSharpRemote(dir string) error {
	content := `// <auto-generated/>
#nullable enable
using System.Text.Json;

namespace GoGit.Interop;

public sealed class Remote : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Remote(long handle) => _handle = handle;

    public string Name
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitRemoteConfigName(_handle, out var namePtr));
            return NativeMethods.ConsumeGoString(namePtr)!;
        }
    }

    public void Fetch(FetchOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRemoteFetch(_handle, options.Handle));
    }

    public void Push(PushOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRemotePush(_handle, options.Handle));
    }

    public ReferenceInfo[] List(ListOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRemoteList(_handle, options.Handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<ReferenceInfo[]>(json) ?? [];
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitRemoteFree(_handle);
        _handle = 0;
    }
}
`
	return os.WriteFile(filepath.Join(dir, "Remote.cs"), []byte(content), 0644)
}

func generateCSharpSubmodule(dir string) error {
	content := `// <auto-generated/>
#nullable enable
namespace GoGit.Interop;

public sealed class Submodule : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Submodule(long handle) => _handle = handle;

    public string Name
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleConfigName(_handle, out var namePtr));
            return NativeMethods.ConsumeGoString(namePtr)!;
        }
    }

    public void Init()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleInit(_handle));
    }

    public void Update(SubmoduleUpdateOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleUpdate(_handle, options.Handle));
    }

    public Repository GetRepository()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleRepository(_handle, out var handle));
        return new Repository(handle);
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitSubmoduleFree(_handle);
        _handle = 0;
    }
}
`
	return os.WriteFile(filepath.Join(dir, "Submodule.cs"), []byte(content), 0644)
}

func generateCSharpAuth(dir string) error {
	content := `// <auto-generated/>
#nullable enable
namespace GoGit.Interop;

public sealed class Auth : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Auth(long handle) => _handle = handle;
    internal long Handle => _handle;

    public static Auth BasicHTTP(string username, string password)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitAuthNewBasicHTTP(username, password, out var handle));
        return new Auth(handle);
    }

    public static Auth TokenHTTP(string token)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitAuthNewTokenHTTP(token, out var handle));
        return new Auth(handle);
    }

    public static Auth SSHKeyFromFile(string user, string pemFile, string password = "")
    {
        NativeMethods.ThrowIfError(NativeMethods.GitAuthNewSSHKeyFromFile(user, pemFile, password, out var handle));
        return new Auth(handle);
    }

    public static Auth SSHKey(string user, string pem, string password = "")
    {
        NativeMethods.ThrowIfError(NativeMethods.GitAuthNewSSHKey(user, pem, password, out var handle));
        return new Auth(handle);
    }

    public static Auth SSHAgent(string user)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitAuthNewSSHAgent(user, out var handle));
        return new Auth(handle);
    }

    public static Auth SSHPassword(string user, string password)
    {
        NativeMethods.ThrowIfError(NativeMethods.GitAuthNewSSHPassword(user, password, out var handle));
        return new Auth(handle);
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitAuthFree(_handle);
        _handle = 0;
    }
}
`
	return os.WriteFile(filepath.Join(dir, "Auth.cs"), []byte(content), 0644)
}

func generateCSharpSigner(dir string) error {
	content := `// <auto-generated/>
#nullable enable
namespace GoGit.Interop;

public sealed class Signer : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Signer(long handle) => _handle = handle;
    internal long Handle => _handle;

    public static Signer FromPGPKey(string armoredKey, string passphrase = "")
    {
        NativeMethods.ThrowIfError(NativeMethods.GitSignerNewPGP(armoredKey, passphrase, out var handle));
        return new Signer(handle);
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitSignerFree(_handle);
        _handle = 0;
    }
}
`
	return os.WriteFile(filepath.Join(dir, "Signer.cs"), []byte(content), 0644)
}

var optionsTemplate = template.Must(template.New("options").Parse(`// <auto-generated/>
#nullable enable
namespace GoGit.Interop;

public sealed class {{.ClassName}} : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public {{.ClassName}}()
    {
        NativeMethods.{{.CPrefix}}New(out _handle);
    }
{{range .Fields}}
    public {{.ClassName}} {{.MethodName}}({{.CSharpParamType}} value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.{{.SetterName}}(_handle, {{.MarshalExpr}}));
        return this;
    }
{{end}}{{range .ExtraSetters}}
    public {{.ClassName}} {{.MethodName}}({{.Params}})
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.{{.NativeMethod}}(_handle, {{.Args}}));
        return this;
    }
{{end}}
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.{{.CPrefix}}Free(_handle);
        _handle = 0;
    }
}
`))

type optionsTemplateData struct {
	ClassName    string
	CPrefix      string
	Fields       []optionsFieldData
	ExtraSetters []extraSetterData
}

type optionsFieldData struct {
	ClassName       string
	MethodName      string
	CSharpParamType string
	SetterName      string
	MarshalExpr     string
}

type extraSetterData struct {
	ClassName    string
	MethodName   string
	Params       string
	NativeMethod string
	Args         string
}

func generateCSharpOptions(pkg *Package, dir string) error {
	optionsDir := filepath.Join(dir, "Options")

	for _, opts := range pkg.Options {
		data := optionsTemplateData{
			ClassName: opts.GoName,
			CPrefix:   opts.CPrefix,
		}

		for _, f := range opts.Fields {
			fd := optionsFieldData{
				ClassName:  opts.GoName,
				MethodName: "Set" + f.GoName,
				SetterName: opts.CPrefix + "Set" + f.GoName,
			}

			switch f.Mapping.Kind {
			case MappingString, MappingReferenceName, MappingHash:
				fd.CSharpParamType = "string"
				fd.MarshalExpr = "value"
			case MappingBool:
				fd.CSharpParamType = "bool"
				fd.MarshalExpr = "value ? 1 : 0"
			case MappingPrimitive, MappingEnum:
				fd.CSharpParamType = "int"
				fd.MarshalExpr = "value"
			case MappingAuth:
				fd.CSharpParamType = "Auth"
				fd.MarshalExpr = "value.Handle"
			case MappingSigner:
				fd.CSharpParamType = "Signer"
				fd.MarshalExpr = "value.Handle"
			default:
				continue
			}

			data.Fields = append(data.Fields, fd)
		}

		// Special extra setters
		if opts.GoName == "CommitOptions" {
			data.ExtraSetters = append(data.ExtraSetters,
				extraSetterData{ClassName: opts.GoName, MethodName: "SetAuthor", Params: "string name, string email",
					NativeMethod: opts.CPrefix + "SetAuthorNameEmail", Args: "name, email"},
				extraSetterData{ClassName: opts.GoName, MethodName: "SetCommitter", Params: "string name, string email",
					NativeMethod: opts.CPrefix + "SetCommitterNameEmail", Args: "name, email"},
			)
		}
		if opts.GoName == "CreateTagOptions" {
			data.ExtraSetters = append(data.ExtraSetters,
				extraSetterData{ClassName: opts.GoName, MethodName: "SetTagger", Params: "string name, string email",
					NativeMethod: opts.CPrefix + "SetTaggerNameEmail", Args: "name, email"},
			)
		}
		if opts.GoName == "RestoreOptions" {
			data.ExtraSetters = append(data.ExtraSetters,
				extraSetterData{ClassName: opts.GoName, MethodName: "AddFile", Params: "string path",
					NativeMethod: opts.CPrefix + "AddFile", Args: "path"},
			)
		}

		var b strings.Builder
		if err := optionsTemplate.Execute(&b, data); err != nil {
			return fmt.Errorf("executing template for %s: %w", opts.GoName, err)
		}

		if err := os.WriteFile(filepath.Join(optionsDir, opts.GoName+".cs"), []byte(b.String()), 0644); err != nil {
			return err
		}
	}

	return nil
}

func generateCSharpIterators(dir string) error {
	iterDir := filepath.Join(dir, "Iterators")

	commitIter := `// <auto-generated/>
#nullable enable
namespace GoGit.Interop;

public sealed class CommitIterator : IEnumerable<Commit>, IDisposable
{
    private long _handle;
    private bool _disposed;

    internal CommitIterator(long handle) => _handle = handle;

    public IEnumerator<Commit> GetEnumerator()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        while (true)
        {
            var err = NativeMethods.GitCommitIterNext(
                _handle,
                out var hash, out var msg, out var name, out var email, out var ts, out var eof);
            NativeMethods.ThrowIfError(err);

            if (eof != 0) yield break;

            yield return new Commit
            {
                Hash = NativeMethods.ConsumeGoString(hash)!,
                Message = NativeMethods.ConsumeGoString(msg)!,
                AuthorName = NativeMethods.ConsumeGoString(name)!,
                AuthorEmail = NativeMethods.ConsumeGoString(email)!,
                AuthorTimestamp = DateTimeOffset.FromUnixTimeSeconds(ts),
            };
        }
    }

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitCommitIterFree(_handle);
        _handle = 0;
    }
}
`
	if err := os.WriteFile(filepath.Join(iterDir, "CommitIterator.cs"), []byte(commitIter), 0644); err != nil {
		return err
	}

	refIter := `// <auto-generated/>
#nullable enable
namespace GoGit.Interop;

public sealed class ReferenceIterator : IEnumerable<ReferenceInfo>, IDisposable
{
    private long _handle;
    private bool _disposed;

    internal ReferenceIterator(long handle) => _handle = handle;

    public IEnumerator<ReferenceInfo> GetEnumerator()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        while (true)
        {
            var err = NativeMethods.GitReferenceIterNext(
                _handle,
                out var refName, out var hash, out var eof);
            NativeMethods.ThrowIfError(err);

            if (eof != 0) yield break;

            yield return new ReferenceInfo
            {
                Name = NativeMethods.ConsumeGoString(refName)!,
                Hash = NativeMethods.ConsumeGoString(hash)!,
            };
        }
    }

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() => GetEnumerator();

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitReferenceIterFree(_handle);
        _handle = 0;
    }
}
`
	return os.WriteFile(filepath.Join(iterDir, "ReferenceIterator.cs"), []byte(refIter), 0644)
}

func generateCSharpModels(dir string) error {
	modelsDir := filepath.Join(dir, "Models")

	commit := `// <auto-generated/>
#nullable enable
namespace GoGit.Interop;

public sealed class Commit
{
    public required string Hash { get; init; }
    public required string Message { get; init; }
    public required string AuthorName { get; init; }
    public required string AuthorEmail { get; init; }
    public required DateTimeOffset AuthorTimestamp { get; init; }
}
`
	if err := os.WriteFile(filepath.Join(modelsDir, "Commit.cs"), []byte(commit), 0644); err != nil {
		return err
	}

	refInfo := `// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace GoGit.Interop;

public sealed class ReferenceInfo
{
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("hash")]
    public required string Hash { get; init; }
}
`
	if err := os.WriteFile(filepath.Join(modelsDir, "ReferenceInfo.cs"), []byte(refInfo), 0644); err != nil {
		return err
	}

	fileStatus := `// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace GoGit.Interop;

public sealed class FileStatus
{
    [JsonPropertyName("staging")]
    public string Staging { get; init; } = "";

    [JsonPropertyName("worktree")]
    public string Worktree { get; init; } = "";

    [JsonPropertyName("extra")]
    public string? Extra { get; init; }
}
`
	return os.WriteFile(filepath.Join(modelsDir, "FileStatus.cs"), []byte(fileStatus), 0644)
}
