// <auto-generated/>
#nullable enable
using System.Text.Json;

namespace GoGit.Interop;

public sealed class Remote : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Remote(long handle) => _handle = handle;

    public string Name
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitRemoteConfigName(_handle, out var namePtr));
            return NativeMethods.ConsumeGoString(namePtr)!;
        }
    }

    public void Fetch(FetchOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRemoteFetch(_handle, options.Handle));
    }

    public void Push(PushOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRemotePush(_handle, options.Handle));
    }

    public ReferenceInfo[] List(ListOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitRemoteList(_handle, options.Handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<ReferenceInfo[]>(json) ?? [];
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitRemoteFree(_handle);
        _handle = 0;
    }
}
