// <auto-generated/>
#nullable enable
namespace GoGit.Interop;

public sealed class Submodule : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Submodule(long handle) => _handle = handle;

    public string Name
    {
        get
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleConfigName(_handle, out var namePtr));
            return NativeMethods.ConsumeGoString(namePtr)!;
        }
    }

    public void Init()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleInit(_handle));
    }

    public void Update(SubmoduleUpdateOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleUpdate(_handle, options.Handle));
    }

    public Repository GetRepository()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleRepository(_handle, out var handle));
        return new Repository(handle);
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitSubmoduleFree(_handle);
        _handle = 0;
    }
}
