// <auto-generated/>
#nullable enable
using System.Text.Json;

namespace GoGit.Interop;

public sealed class Worktree : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal Worktree(long handle) => _handle = handle;

    public Dictionary<string, FileStatus> Status()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeStatus(_handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<Dictionary<string, FileStatus>>(json) ?? new();
    }

    public string Add(string path)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeAdd(_handle, path, out var hash));
        return NativeMethods.ConsumeGoString(hash)!;
    }

    public void AddWithOptions(AddOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeAddWithOptions(_handle, options.Handle));
    }

    public void AddGlob(string pattern)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeAddGlob(_handle, pattern));
    }

    public string Commit(string message, CommitOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeCommit(_handle, message, options.Handle, out var hash));
        return NativeMethods.ConsumeGoString(hash)!;
    }

    public void Checkout(CheckoutOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeCheckout(_handle, options.Handle));
    }

    public void Pull(PullOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreePull(_handle, options.Handle));
    }

    public void Reset(ResetOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeReset(_handle, options.Handle));
    }

    public void Restore(RestoreOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeRestore(_handle, options.Handle));
    }

    public void Clean(CleanOptions options)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeClean(_handle, options.Handle));
    }

    public string Move(string from, string to)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeMove(_handle, from, to, out var hash));
        return NativeMethods.ConsumeGoString(hash)!;
    }

    public Submodule GetSubmodule(string name)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeSubmodule(_handle, name, out var handle));
        return new Submodule(handle);
    }

    public string[] Submodules()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitWorktreeSubmodules(_handle, out var jsonPtr));
        var json = NativeMethods.ConsumeGoString(jsonPtr)!;
        return JsonSerializer.Deserialize<string[]>(json) ?? [];
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitWorktreeFree(_handle);
        _handle = 0;
    }
}
