// Code generated by gogit-interop/generate. DO NOT EDIT.
package main

/*
#include <stdlib.h>
#include "callbacks.h"
*/
import "C"
import (
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"unsafe"

	"github.com/go-git/go-git/v6/plumbing/transport/http"
	"github.com/go-git/go-git/v6/plumbing/transport/ssh"
	stdssh "golang.org/x/crypto/ssh"
)

func setSSHHostKeyCallback(authHandle C.longlong, cb stdssh.HostKeyCallback) *C.char {
	h, ok := loadHandle[interface{}](int64(authHandle))
	if !ok {
		return C.CString("invalid auth handle")
	}
	switch a := h.(type) {
	case *ssh.PublicKeys:
		a.HostKeyCallback = cb
	case *ssh.PublicKeysCallback:
		a.HostKeyCallback = cb
	case *ssh.Password:
		a.HostKeyCallback = cb
	case *ssh.PasswordCallback:
		a.HostKeyCallback = cb
	case *ssh.KeyboardInteractive:
		a.HostKeyCallback = cb
	default:
		return C.CString(fmt.Sprintf("auth type %T does not support HostKeyCallback", h))
	}
	return nil
}

//export GitAuthSetInsecureIgnoreHostKey
func GitAuthSetInsecureIgnoreHostKey(authHandle C.longlong) *C.char {
	return setSSHHostKeyCallback(authHandle, stdssh.InsecureIgnoreHostKey())
}

//export GitAuthSetKnownHostsFiles
func GitAuthSetKnownHostsFiles(authHandle C.longlong, filesJSON *C.char) *C.char {
	var paths []string
	if err := json.Unmarshal([]byte(C.GoString(filesJSON)), &paths); err != nil {
		return toCError(err)
	}
	cb, err := ssh.NewKnownHostsCallback(paths...)
	if err != nil {
		return toCError(err)
	}
	return setSSHHostKeyCallback(authHandle, cb)
}

//export GitAuthSetHostKeyCallback
func GitAuthSetHostKeyCallback(authHandle C.longlong, fn C.GitHostKeyFunc, userData unsafe.Pointer) *C.char {
	cb := func(hostname string, remote net.Addr, key stdssh.PublicKey) error {
		keyType := key.Type()
		keyBytes := base64.StdEncoding.EncodeToString(key.Marshal())

		cHostname := C.CString(hostname)
		defer C.free(unsafe.Pointer(cHostname))
		cRemote := C.CString(remote.String())
		defer C.free(unsafe.Pointer(cRemote))
		cKeyType := C.CString(keyType)
		defer C.free(unsafe.Pointer(cKeyType))
		cKeyB64 := C.CString(keyBytes)
		defer C.free(unsafe.Pointer(cKeyB64))

		errStr := C.callHostKeyFunc(fn, cHostname, cRemote, cKeyType, cKeyB64, userData)
		if errStr != nil {
			defer C.free(unsafe.Pointer(errStr))
			return errors.New(C.GoString(errStr))
		}
		return nil
	}
	return setSSHHostKeyCallback(authHandle, cb)
}

//export GitAuthNewBasicHTTP
func GitAuthNewBasicHTTP(username *C.char, password *C.char, handleOut *C.longlong) *C.char {
	auth := &http.BasicAuth{
		Username: C.GoString(username),
		Password: C.GoString(password),
	}
	*handleOut = C.longlong(storeHandle(auth))
	return nil
}

//export GitAuthNewTokenHTTP
func GitAuthNewTokenHTTP(token *C.char, handleOut *C.longlong) *C.char {
	auth := &http.TokenAuth{
		Token: C.GoString(token),
	}
	*handleOut = C.longlong(storeHandle(auth))
	return nil
}

//export GitAuthNewSSHKeyFromFile
func GitAuthNewSSHKeyFromFile(user *C.char, pemFile *C.char, password *C.char, handleOut *C.longlong) *C.char {
	auth, err := ssh.NewPublicKeysFromFile(C.GoString(user), C.GoString(pemFile), C.GoString(password))
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(auth))
	return nil
}

//export GitAuthNewSSHKey
func GitAuthNewSSHKey(user *C.char, pem *C.char, password *C.char, handleOut *C.longlong) *C.char {
	auth, err := ssh.NewPublicKeys(C.GoString(user), []byte(C.GoString(pem)), C.GoString(password))
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(auth))
	return nil
}

//export GitAuthNewSSHAgent
func GitAuthNewSSHAgent(user *C.char, handleOut *C.longlong) *C.char {
	auth, err := ssh.NewSSHAgentAuth(C.GoString(user))
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(auth))
	return nil
}

//export GitAuthNewSSHPassword
func GitAuthNewSSHPassword(user *C.char, password *C.char, handleOut *C.longlong) *C.char {
	auth := &ssh.Password{
		User:     C.GoString(user),
		Password: C.GoString(password),
	}
	*handleOut = C.longlong(storeHandle(auth))
	return nil
}

//export GitAuthFree
func GitAuthFree(handle C.longlong) {
	removeHandle(int64(handle))
}
