// Code generated by gogit-interop/generate. DO NOT EDIT.
package main

/*
#include <stdlib.h>
*/
import "C"
import (
	"github.com/go-git/go-git/v6/plumbing/object"
	"github.com/go-git/go-git/v6/plumbing"
	"time"
	"encoding/json"
)

//export GitCommitFile
func GitCommitFile(cHandle C.longlong, path *C.char, handleOut *C.longlong) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	r0, err := recv.File(C.GoString(path))
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitCommitFiles
func GitCommitFiles(cHandle C.longlong, iterOut *C.longlong) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	r0, err := recv.Files()
	if err != nil {
		return toCError(err)
	}
	*iterOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitCommitID
func GitCommitID(cHandle C.longlong, refNameOut **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	r0 := recv.ID()
	*refNameOut = C.CString(r0.String())
	return nil
}

//export GitCommitIsAncestor
func GitCommitIsAncestor(cHandle C.longlong, otherHandle C.longlong, out0 *C.int) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	r0, err := recv.IsAncestor(func() *object.Commit { v, _ := loadHandle[*object.Commit](int64(otherHandle)); return v }())
	if err != nil {
		return toCError(err)
	}
	if r0 {
		*out0 = 1
	} else {
		*out0 = 0
	}
	return nil
}

//export GitCommitLess
func GitCommitLess(cHandle C.longlong, rhsHandle C.longlong, out0 *C.int) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	r0 := recv.Less(func() *object.Commit { v, _ := loadHandle[*object.Commit](int64(rhsHandle)); return v }())
	if r0 {
		*out0 = 1
	} else {
		*out0 = 0
	}
	return nil
}

//export GitCommitMergeBase
func GitCommitMergeBase(cHandle C.longlong, otherHandle C.longlong, jsonOut **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	other, ok := loadHandle[*object.Commit](int64(otherHandle))
	if !ok {
		return C.CString("invalid other commit handle")
	}
	bases, err := recv.MergeBase(other)
	if err != nil {
		return toCError(err)
	}
	hashes := make([]string, len(bases))
	for i, c := range bases {
		hashes[i] = c.Hash.String()
	}
	data, err := json.Marshal(hashes)
	if err != nil {
		return toCError(err)
	}
	*jsonOut = C.CString(string(data))
	return nil
}

//export GitCommitNumParents
func GitCommitNumParents(cHandle C.longlong, out0 *C.int) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	r0 := recv.NumParents()
	*out0 = C.int(r0)
	return nil
}

//export GitCommitParent
func GitCommitParent(cHandle C.longlong, i C.int, handleOut *C.longlong) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	r0, err := recv.Parent(int(i))
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitCommitParents
func GitCommitParents(cHandle C.longlong, iterOut *C.longlong) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	r0 := recv.Parents()
	*iterOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitCommitPatch
func GitCommitPatch(cHandle C.longlong, toHandle C.longlong, patchOut **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	var to *object.Commit
	if int64(toHandle) != 0 {
		var ok bool
		to, ok = loadHandle[*object.Commit](int64(toHandle))
		if !ok {
			return C.CString("invalid to-commit handle")
		}
	}
	patch, err := recv.Patch(to)
	if err != nil {
		return toCError(err)
	}
	*patchOut = C.CString(patch.String())
	return nil
}

//export GitCommitStats
func GitCommitStats(cHandle C.longlong, jsonOut **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	stats, err := recv.Stats()
	if err != nil {
		return toCError(err)
	}
	type fileStatJSON struct {
		Name     string `json:"name"`
		Addition int    `json:"addition"`
		Deletion int    `json:"deletion"`
	}
	out := make([]fileStatJSON, len(stats))
	for i, s := range stats {
		out[i] = fileStatJSON{Name: s.Name, Addition: s.Addition, Deletion: s.Deletion}
	}
	data, err := json.Marshal(out)
	if err != nil {
		return toCError(err)
	}
	*jsonOut = C.CString(string(data))
	return nil
}

//export GitCommitString
func GitCommitString(cHandle C.longlong, refNameOut **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	r0 := recv.String()
	*refNameOut = C.CString(r0)
	return nil
}

//export GitCommitTree
func GitCommitTree(cHandle C.longlong, handleOut *C.longlong) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	r0, err := recv.Tree()
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitCommitType
func GitCommitType(cHandle C.longlong, out0 *C.int) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	r0 := recv.Type()
	*out0 = C.int(r0)
	return nil
}

//export GitCommitVerify
func GitCommitVerify(cHandle C.longlong, armoredKeyRing *C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	_, err := recv.Verify(C.GoString(armoredKeyRing))
	if err != nil {
		return toCError(err)
	}
	return nil
}

//export GitCommitAuthorName
func GitCommitAuthorName(cHandle C.longlong, out **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	*out = C.CString(recv.Author.Name)
	return nil
}

//export GitCommitAuthorEmail
func GitCommitAuthorEmail(cHandle C.longlong, out **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	*out = C.CString(recv.Author.Email)
	return nil
}

//export GitCommitAuthorWhen
func GitCommitAuthorWhen(cHandle C.longlong, tsOut *C.longlong) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	*tsOut = C.longlong(recv.Author.When.Unix())
	return nil
}

//export GitCommitCommitterName
func GitCommitCommitterName(cHandle C.longlong, out **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	*out = C.CString(recv.Committer.Name)
	return nil
}

//export GitCommitCommitterEmail
func GitCommitCommitterEmail(cHandle C.longlong, out **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	*out = C.CString(recv.Committer.Email)
	return nil
}

//export GitCommitCommitterWhen
func GitCommitCommitterWhen(cHandle C.longlong, tsOut *C.longlong) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	*tsOut = C.longlong(recv.Committer.When.Unix())
	return nil
}

//export GitCommitGetHash
func GitCommitGetHash(cHandle C.longlong, out **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	*out = C.CString(recv.Hash.String())
	return nil
}

//export GitCommitGetMergeTag
func GitCommitGetMergeTag(cHandle C.longlong, out **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	*out = C.CString(string(recv.MergeTag))
	return nil
}

//export GitCommitGetSignature
func GitCommitGetSignature(cHandle C.longlong, out **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	*out = C.CString(string(recv.Signature))
	return nil
}

//export GitCommitGetMessage
func GitCommitGetMessage(cHandle C.longlong, out **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	*out = C.CString(string(recv.Message))
	return nil
}

//export GitCommitGetTreeHash
func GitCommitGetTreeHash(cHandle C.longlong, out **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	*out = C.CString(recv.TreeHash.String())
	return nil
}

//export GitCommitGetEncoding
func GitCommitGetEncoding(cHandle C.longlong, out **C.char) *C.char {
	recv, ok := loadHandle[*object.Commit](int64(cHandle))
	if !ok {
		return C.CString("invalid commit handle")
	}
	*out = C.CString(string(recv.Encoding))
	return nil
}

//export GitCommitFree
func GitCommitFree(cHandle C.longlong) {
	removeHandle(int64(cHandle))
}

var (
	_ = json.Marshal
	_ object.Signature
	_ plumbing.Hash
	_ = time.Now
)
