// Code generated by gogit-interop/generate. DO NOT EDIT.
package main

/*
#include <stdlib.h>
*/
import "C"
import (
	"encoding/json"
	"github.com/go-git/go-git/v6/plumbing/object"
)

//export GitFileContents
func GitFileContents(fHandle C.longlong, refNameOut **C.char) *C.char {
	recv, ok := loadHandle[*object.File](int64(fHandle))
	if !ok {
		return C.CString("invalid file handle")
	}
	r0, err := recv.Contents()
	if err != nil {
		return toCError(err)
	}
	*refNameOut = C.CString(r0)
	return nil
}

//export GitFileIsBinary
func GitFileIsBinary(fHandle C.longlong, out0 *C.int) *C.char {
	recv, ok := loadHandle[*object.File](int64(fHandle))
	if !ok {
		return C.CString("invalid file handle")
	}
	r0, err := recv.IsBinary()
	if err != nil {
		return toCError(err)
	}
	if r0 {
		*out0 = 1
	} else {
		*out0 = 0
	}
	return nil
}

//export GitFileLines
func GitFileLines(fHandle C.longlong, out0 **C.char) *C.char {
	recv, ok := loadHandle[*object.File](int64(fHandle))
	if !ok {
		return C.CString("invalid file handle")
	}
	r0, err := recv.Lines()
	if err != nil {
		return toCError(err)
	}
	{ d, _ := json.Marshal(r0); *out0 = C.CString(string(d)) }
	return nil
}

//export GitFileGetName
func GitFileGetName(fHandle C.longlong, out **C.char) *C.char {
	recv, ok := loadHandle[*object.File](int64(fHandle))
	if !ok {
		return C.CString("invalid file handle")
	}
	*out = C.CString(string(recv.Name))
	return nil
}

//export GitFileGetMode
func GitFileGetMode(fHandle C.longlong, out *C.uint) *C.char {
	recv, ok := loadHandle[*object.File](int64(fHandle))
	if !ok {
		return C.CString("invalid file handle")
	}
	*out = C.uint(recv.Mode)
	return nil
}

//export GitFileFree
func GitFileFree(fHandle C.longlong) {
	removeHandle(int64(fHandle))
}

var (
	_ = json.Marshal
	_ object.Signature
)
