// Code generated by gogit-interop/generate. DO NOT EDIT.
package main

/*
#include <stdlib.h>
*/
import "C"
import (
	"github.com/go-git/go-git/v6/storage/memory"
	"encoding/json"
	git "github.com/go-git/go-git/v6"
	"context"
	"github.com/go-git/go-git/v6/config"
)

//export GitRemoteFetch
func GitRemoteFetch(rHandle C.longlong, oHandle C.longlong) *C.char {
	recv, ok := loadHandle[*git.Remote](int64(rHandle))
	if !ok {
		return C.CString("invalid remote handle")
	}
	return toCError(recv.Fetch(func() *git.FetchOptions { if int64(oHandle) == 0 { return nil }; v, _ := loadHandle[*git.FetchOptions](int64(oHandle)); return v }()))
}

//export GitRemoteFetchContext
func GitRemoteFetchContext(rHandle C.longlong, oHandle C.longlong) *C.char {
	recv, ok := loadHandle[*git.Remote](int64(rHandle))
	if !ok {
		return C.CString("invalid remote handle")
	}
	return toCError(recv.FetchContext(context.Background(), func() *git.FetchOptions { if int64(oHandle) == 0 { return nil }; v, _ := loadHandle[*git.FetchOptions](int64(oHandle)); return v }()))
}

//export GitRemoteList
func GitRemoteList(remoteHandle C.longlong, optsHandle C.longlong, jsonOut **C.char) *C.char {
	recv, ok := loadHandle[*git.Remote](int64(remoteHandle))
	if !ok {
		return C.CString("invalid remote handle")
	}
	opts, ok := loadHandle[*git.ListOptions](int64(optsHandle))
	if !ok {
		return C.CString("invalid ListOptions handle")
	}
	refs, err := recv.List(opts)
	if err != nil {
		return toCError(err)
	}
	type refJSON struct {
		Name string `json:"name"`
		Hash string `json:"hash"`
	}
	out := make([]refJSON, len(refs))
	for i, r := range refs {
		out[i] = refJSON{Name: string(r.Name()), Hash: r.Hash().String()}
	}
	data, err := json.Marshal(out)
	if err != nil {
		return toCError(err)
	}
	*jsonOut = C.CString(string(data))
	return nil
}

//export GitRemotePush
func GitRemotePush(rHandle C.longlong, oHandle C.longlong) *C.char {
	recv, ok := loadHandle[*git.Remote](int64(rHandle))
	if !ok {
		return C.CString("invalid remote handle")
	}
	return toCError(recv.Push(func() *git.PushOptions { if int64(oHandle) == 0 { return nil }; v, _ := loadHandle[*git.PushOptions](int64(oHandle)); return v }()))
}

//export GitRemotePushContext
func GitRemotePushContext(rHandle C.longlong, oHandle C.longlong) *C.char {
	recv, ok := loadHandle[*git.Remote](int64(rHandle))
	if !ok {
		return C.CString("invalid remote handle")
	}
	return toCError(recv.PushContext(context.Background(), func() *git.PushOptions { if int64(oHandle) == 0 { return nil }; v, _ := loadHandle[*git.PushOptions](int64(oHandle)); return v }()))
}

//export GitRemoteString
func GitRemoteString(rHandle C.longlong, refNameOut **C.char) *C.char {
	recv, ok := loadHandle[*git.Remote](int64(rHandle))
	if !ok {
		return C.CString("invalid remote handle")
	}
	r0 := recv.String()
	*refNameOut = C.CString(r0)
	return nil
}

//export GitNewRemote
func GitNewRemote(url *C.char, handleOut *C.longlong) *C.char {
	remote := git.NewRemote(memory.NewStorage(), &config.RemoteConfig{
		Name: "origin",
		URLs: []string{C.GoString(url)},
	})
	*handleOut = C.longlong(storeHandle(remote))
	return nil
}

//export GitRemoteConfigName
func GitRemoteConfigName(remoteHandle C.longlong, nameOut **C.char) *C.char {
	remote, ok := loadHandle[*git.Remote](int64(remoteHandle))
	if !ok {
		return C.CString("invalid remote handle")
	}
	*nameOut = C.CString(remote.Config().Name)
	return nil
}

//export GitRemoteConfig
func GitRemoteConfig(remoteHandle C.longlong, jsonOut **C.char) *C.char {
	remote, ok := loadHandle[*git.Remote](int64(remoteHandle))
	if !ok {
		return C.CString("invalid remote handle")
	}
	cfg := remote.Config()
	type remoteConfigJSON struct {
		Name  string   `json:"name"`
		URLs  []string `json:"urls"`
		Fetch []string `json:"fetch"`
	}
	fetchSpecs := make([]string, len(cfg.Fetch))
	for i, f := range cfg.Fetch {
		fetchSpecs[i] = string(f)
	}
	out := remoteConfigJSON{Name: cfg.Name, URLs: cfg.URLs, Fetch: fetchSpecs}
	data, err := json.Marshal(out)
	if err != nil {
		return toCError(err)
	}
	*jsonOut = C.CString(string(data))
	return nil
}

//export GitRemoteFree
func GitRemoteFree(rHandle C.longlong) {
	removeHandle(int64(rHandle))
}

var (
	_ = json.Marshal
	_ = memory.NewStorage
	_ = context.Background
	_ config.RemoteConfig
)
