// Code generated by gogit-interop/generate. DO NOT EDIT.
package main

/*
#include <stdlib.h>
*/
import "C"
import (
	"context"
	"encoding/json"
	git "github.com/go-git/go-git/v6"
	"github.com/go-git/go-git/v6/config"
	"github.com/go-git/go-git/v6/plumbing"
	"github.com/go-git/go-git/v6/plumbing/object"
	"github.com/go-git/go-git/v6/plumbing/storer"
	"github.com/go-git/go-git/v6/plumbing/transport"
)

//export GitPlainClone
func GitPlainClone(path *C.char, oHandle C.longlong, handleOut *C.longlong) *C.char {
	result, err := git.PlainClone(C.GoString(path), func() *git.CloneOptions { v, _ := loadHandle[*git.CloneOptions](int64(oHandle)); return v }())
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(result))
	return nil
}

//export GitPlainCloneContext
func GitPlainCloneContext(path *C.char, oHandle C.longlong, handleOut *C.longlong) *C.char {
	result, err := git.PlainCloneContext(context.Background(), C.GoString(path), func() *git.CloneOptions { v, _ := loadHandle[*git.CloneOptions](int64(oHandle)); return v }())
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(result))
	return nil
}

//export GitPlainInit
func GitPlainInit(path *C.char, isBare C.int, handleOut *C.longlong) *C.char {
	result, err := git.PlainInit(C.GoString(path), isBare != 0)
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(result))
	return nil
}

//export GitPlainOpen
func GitPlainOpen(path *C.char, handleOut *C.longlong) *C.char {
	result, err := git.PlainOpen(C.GoString(path))
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(result))
	return nil
}

//export GitPlainOpenWithOptions
func GitPlainOpenWithOptions(path *C.char, oHandle C.longlong, handleOut *C.longlong) *C.char {
	result, err := git.PlainOpenWithOptions(C.GoString(path), func() *git.PlainOpenOptions { v, _ := loadHandle[*git.PlainOpenOptions](int64(oHandle)); return v }())
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(result))
	return nil
}

//export GitRepositoryBranches
func GitRepositoryBranches(rHandle C.longlong, iterOut *C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	r0, err := recv.Branches()
	if err != nil {
		return toCError(err)
	}
	*iterOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitRepositoryCommitObject
func GitRepositoryCommitObject(repoHandle C.longlong, hash *C.char, commitHashOut **C.char, msgOut **C.char, authorNameOut **C.char, authorEmailOut **C.char, tsOut *C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(repoHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	h := plumbing.NewHash(C.GoString(hash))
	commit, err := recv.CommitObject(h)
	if err != nil {
		return toCError(err)
	}
	*commitHashOut = C.CString(commit.Hash.String())
	*msgOut = C.CString(commit.Message)
	*authorNameOut = C.CString(commit.Author.Name)
	*authorEmailOut = C.CString(commit.Author.Email)
	*tsOut = C.longlong(commit.Author.When.Unix())
	return nil
}

//export GitRepositoryCommitObjects
func GitRepositoryCommitObjects(rHandle C.longlong, iterOut *C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	r0, err := recv.CommitObjects()
	if err != nil {
		return toCError(err)
	}
	*iterOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitRepositoryCreateBranch
func GitRepositoryCreateBranch(repoHandle C.longlong, name *C.char, hash *C.char) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(repoHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	branch := &config.Branch{
		Name: C.GoString(name),
	}
	return toCError(recv.CreateBranch(branch))
}

//export GitRepositoryCreateRemote
func GitRepositoryCreateRemote(repoHandle C.longlong, name *C.char, url *C.char, handleOut *C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(repoHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	remote, err := recv.CreateRemote(&config.RemoteConfig{
		Name: C.GoString(name),
		URLs: []string{C.GoString(url)},
	})
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(remote))
	return nil
}

//export GitRepositoryCreateTag
func GitRepositoryCreateTag(rHandle C.longlong, name *C.char, hash *C.char, optsHandle C.longlong, refNameOut **C.char, hashOut **C.char) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	r0, err := recv.CreateTag(C.GoString(name), plumbing.NewHash(C.GoString(hash)), func() *git.CreateTagOptions {
		if int64(optsHandle) == 0 {
			return nil
		}
		v, _ := loadHandle[*git.CreateTagOptions](int64(optsHandle))
		return v
	}())
	if err != nil {
		return toCError(err)
	}
	*refNameOut = C.CString(string(r0.Name()))
	*hashOut = C.CString(r0.Hash().String())
	return nil
}

//export GitRepositoryDeleteBranch
func GitRepositoryDeleteBranch(rHandle C.longlong, name *C.char) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	return toCError(recv.DeleteBranch(C.GoString(name)))
}

//export GitRepositoryDeleteObject
func GitRepositoryDeleteObject(rHandle C.longlong, hash *C.char) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	return toCError(recv.DeleteObject(plumbing.NewHash(C.GoString(hash))))
}

//export GitRepositoryDeleteRemote
func GitRepositoryDeleteRemote(rHandle C.longlong, name *C.char) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	return toCError(recv.DeleteRemote(C.GoString(name)))
}

//export GitRepositoryDeleteTag
func GitRepositoryDeleteTag(rHandle C.longlong, name *C.char) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	return toCError(recv.DeleteTag(C.GoString(name)))
}

//export GitRepositoryFetch
func GitRepositoryFetch(rHandle C.longlong, oHandle C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	return toCError(recv.Fetch(func() *git.FetchOptions {
		if int64(oHandle) == 0 {
			return nil
		}
		v, _ := loadHandle[*git.FetchOptions](int64(oHandle))
		return v
	}()))
}

//export GitRepositoryFetchContext
func GitRepositoryFetchContext(rHandle C.longlong, oHandle C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	return toCError(recv.FetchContext(context.Background(), func() *git.FetchOptions {
		if int64(oHandle) == 0 {
			return nil
		}
		v, _ := loadHandle[*git.FetchOptions](int64(oHandle))
		return v
	}()))
}

//export GitRepositoryHead
func GitRepositoryHead(rHandle C.longlong, refNameOut **C.char, hashOut **C.char) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	r0, err := recv.Head()
	if err != nil {
		return toCError(err)
	}
	*refNameOut = C.CString(string(r0.Name()))
	*hashOut = C.CString(r0.Hash().String())
	return nil
}

//export GitRepositoryLog
func GitRepositoryLog(rHandle C.longlong, oHandle C.longlong, iterOut *C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	r0, err := recv.Log(func() *git.LogOptions {
		if int64(oHandle) == 0 {
			return nil
		}
		v, _ := loadHandle[*git.LogOptions](int64(oHandle))
		return v
	}())
	if err != nil {
		return toCError(err)
	}
	*iterOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitRepositoryMerge
func GitRepositoryMerge(repoHandle C.longlong, refName *C.char, hash *C.char, optsHandle C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(repoHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	h := plumbing.NewHash(C.GoString(hash))
	ref := plumbing.NewHashReference(plumbing.ReferenceName(C.GoString(refName)), h)
	var opts git.MergeOptions
	if int64(optsHandle) != 0 {
		optsPtr, ok := loadHandle[*git.MergeOptions](int64(optsHandle))
		if !ok {
			return C.CString("invalid MergeOptions handle")
		}
		opts = *optsPtr
	}
	return toCError(recv.Merge(*ref, opts))
}

//export GitRepositoryNotes
func GitRepositoryNotes(rHandle C.longlong, iterOut *C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	r0, err := recv.Notes()
	if err != nil {
		return toCError(err)
	}
	*iterOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitRepositoryPush
func GitRepositoryPush(rHandle C.longlong, oHandle C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	return toCError(recv.Push(func() *git.PushOptions {
		if int64(oHandle) == 0 {
			return nil
		}
		v, _ := loadHandle[*git.PushOptions](int64(oHandle))
		return v
	}()))
}

//export GitRepositoryPushContext
func GitRepositoryPushContext(rHandle C.longlong, oHandle C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	return toCError(recv.PushContext(context.Background(), func() *git.PushOptions {
		if int64(oHandle) == 0 {
			return nil
		}
		v, _ := loadHandle[*git.PushOptions](int64(oHandle))
		return v
	}()))
}

//export GitRepositoryReference
func GitRepositoryReference(rHandle C.longlong, name *C.char, resolved C.int, refNameOut **C.char, hashOut **C.char) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	r0, err := recv.Reference(plumbing.ReferenceName(C.GoString(name)), resolved != 0)
	if err != nil {
		return toCError(err)
	}
	*refNameOut = C.CString(string(r0.Name()))
	*hashOut = C.CString(r0.Hash().String())
	return nil
}

//export GitRepositoryReferences
func GitRepositoryReferences(rHandle C.longlong, iterOut *C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	r0, err := recv.References()
	if err != nil {
		return toCError(err)
	}
	*iterOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitRepositoryRemote
func GitRepositoryRemote(rHandle C.longlong, name *C.char, handleOut *C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	r0, err := recv.Remote(C.GoString(name))
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitRepositoryResolveRevision
func GitRepositoryResolveRevision(rHandle C.longlong, in *C.char, refNameOut **C.char) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	r0, err := recv.ResolveRevision(plumbing.Revision(C.GoString(in)))
	if err != nil {
		return toCError(err)
	}
	*refNameOut = C.CString(r0.String())
	return nil
}

//export GitRepositoryTag
func GitRepositoryTag(rHandle C.longlong, name *C.char, refNameOut **C.char, hashOut **C.char) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	r0, err := recv.Tag(C.GoString(name))
	if err != nil {
		return toCError(err)
	}
	*refNameOut = C.CString(string(r0.Name()))
	*hashOut = C.CString(r0.Hash().String())
	return nil
}

//export GitRepositoryTags
func GitRepositoryTags(rHandle C.longlong, iterOut *C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	r0, err := recv.Tags()
	if err != nil {
		return toCError(err)
	}
	*iterOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitRepositoryWorktree
func GitRepositoryWorktree(rHandle C.longlong, handleOut *C.longlong) *C.char {
	recv, ok := loadHandle[*git.Repository](int64(rHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	r0, err := recv.Worktree()
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitRepositoryRemotes
func GitRepositoryRemotes(repoHandle C.longlong, jsonOut **C.char) *C.char {
	repo, ok := loadHandle[*git.Repository](int64(repoHandle))
	if !ok {
		return C.CString("invalid repository handle")
	}
	remotes, err := repo.Remotes()
	if err != nil {
		return toCError(err)
	}
	names := make([]string, len(remotes))
	for i, r := range remotes {
		names[i] = r.Config().Name
	}
	data, err := json.Marshal(names)
	if err != nil {
		return toCError(err)
	}
	*jsonOut = C.CString(string(data))
	return nil
}

//export GitRepositoryFree
func GitRepositoryFree(rHandle C.longlong) {
	removeHandle(int64(rHandle))
}

var (
	_ = json.Marshal
	_ storer.ReferenceIter
	_ object.Signature
	_ plumbing.Hash
	_ = context.Background
	_ config.RemoteConfig
	_ transport.AuthMethod
)
