// Code generated by gogit-interop/generate. DO NOT EDIT.
package main

/*
#include <stdlib.h>
*/
import "C"
import (
	"encoding/json"
	"github.com/go-git/go-git/v6/plumbing/object"
	"github.com/go-git/go-git/v6/plumbing"
)

//export GitTreeDiff
func GitTreeDiff(tHandle C.longlong, toHandle C.longlong, jsonOut **C.char) *C.char {
	recv, ok := loadHandle[*object.Tree](int64(tHandle))
	if !ok {
		return C.CString("invalid tree handle")
	}
	var to *object.Tree
	if int64(toHandle) != 0 {
		var ok bool
		to, ok = loadHandle[*object.Tree](int64(toHandle))
		if !ok {
			return C.CString("invalid to-tree handle")
		}
	}
	changes, err := recv.Diff(to)
	if err != nil {
		return toCError(err)
	}
	type changeJSON struct {
		Action   string `json:"action"`
		FromPath string `json:"fromPath,omitempty"`
		ToPath   string `json:"toPath,omitempty"`
		FromHash string `json:"fromHash,omitempty"`
		ToHash   string `json:"toHash,omitempty"`
	}
	out := make([]changeJSON, len(changes))
	for i, ch := range changes {
		c := changeJSON{}
		switch {
		case ch.From.Name == "" && ch.To.Name != "":
			c.Action = "Insert"
		case ch.From.Name != "" && ch.To.Name == "":
			c.Action = "Delete"
		default:
			c.Action = "Modify"
		}
		if ch.From.Name != "" {
			c.FromPath = ch.From.Name
			c.FromHash = ch.From.TreeEntry.Hash.String()
		}
		if ch.To.Name != "" {
			c.ToPath = ch.To.Name
			c.ToHash = ch.To.TreeEntry.Hash.String()
		}
		out[i] = c
	}
	data, err := json.Marshal(out)
	if err != nil {
		return toCError(err)
	}
	*jsonOut = C.CString(string(data))
	return nil
}

//export GitTreeFile
func GitTreeFile(tHandle C.longlong, path *C.char, handleOut *C.longlong) *C.char {
	recv, ok := loadHandle[*object.Tree](int64(tHandle))
	if !ok {
		return C.CString("invalid tree handle")
	}
	r0, err := recv.File(C.GoString(path))
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitTreeFiles
func GitTreeFiles(tHandle C.longlong, iterOut *C.longlong) *C.char {
	recv, ok := loadHandle[*object.Tree](int64(tHandle))
	if !ok {
		return C.CString("invalid tree handle")
	}
	r0 := recv.Files()
	*iterOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitTreeFindEntry
func GitTreeFindEntry(tHandle C.longlong, path *C.char, jsonOut **C.char) *C.char {
	recv, ok := loadHandle[*object.Tree](int64(tHandle))
	if !ok {
		return C.CString("invalid tree handle")
	}
	entry, err := recv.FindEntry(C.GoString(path))
	if err != nil {
		return toCError(err)
	}
	type entryJSON struct {
		Name string `json:"name"`
		Hash string `json:"hash"`
		Mode uint32 `json:"mode"`
	}
	out := entryJSON{
		Name: entry.Name,
		Hash: entry.Hash.String(),
		Mode: uint32(entry.Mode),
	}
	data, err := json.Marshal(out)
	if err != nil {
		return toCError(err)
	}
	*jsonOut = C.CString(string(data))
	return nil
}

//export GitTreeID
func GitTreeID(tHandle C.longlong, refNameOut **C.char) *C.char {
	recv, ok := loadHandle[*object.Tree](int64(tHandle))
	if !ok {
		return C.CString("invalid tree handle")
	}
	r0 := recv.ID()
	*refNameOut = C.CString(r0.String())
	return nil
}

//export GitTreePatch
func GitTreePatch(tHandle C.longlong, toHandle C.longlong, patchOut **C.char) *C.char {
	recv, ok := loadHandle[*object.Tree](int64(tHandle))
	if !ok {
		return C.CString("invalid tree handle")
	}
	var to *object.Tree
	if int64(toHandle) != 0 {
		var ok bool
		to, ok = loadHandle[*object.Tree](int64(toHandle))
		if !ok {
			return C.CString("invalid to-tree handle")
		}
	}
	patch, err := recv.Patch(to)
	if err != nil {
		return toCError(err)
	}
	*patchOut = C.CString(patch.String())
	return nil
}

//export GitTreeSize
func GitTreeSize(tHandle C.longlong, path *C.char, out0 *C.longlong) *C.char {
	recv, ok := loadHandle[*object.Tree](int64(tHandle))
	if !ok {
		return C.CString("invalid tree handle")
	}
	r0, err := recv.Size(C.GoString(path))
	if err != nil {
		return toCError(err)
	}
	*out0 = C.longlong(r0)
	return nil
}

//export GitTreeTree
func GitTreeTree(tHandle C.longlong, path *C.char, handleOut *C.longlong) *C.char {
	recv, ok := loadHandle[*object.Tree](int64(tHandle))
	if !ok {
		return C.CString("invalid tree handle")
	}
	r0, err := recv.Tree(C.GoString(path))
	if err != nil {
		return toCError(err)
	}
	*handleOut = C.longlong(storeHandle(r0))
	return nil
}

//export GitTreeType
func GitTreeType(tHandle C.longlong, out0 *C.int) *C.char {
	recv, ok := loadHandle[*object.Tree](int64(tHandle))
	if !ok {
		return C.CString("invalid tree handle")
	}
	r0 := recv.Type()
	*out0 = C.int(r0)
	return nil
}

//export GitTreeGetHash
func GitTreeGetHash(tHandle C.longlong, out **C.char) *C.char {
	recv, ok := loadHandle[*object.Tree](int64(tHandle))
	if !ok {
		return C.CString("invalid tree handle")
	}
	*out = C.CString(recv.Hash.String())
	return nil
}

//export GitTreeFree
func GitTreeFree(tHandle C.longlong) {
	removeHandle(int64(tHandle))
}

var (
	_ = json.Marshal
	_ object.Signature
	_ plumbing.Hash
)
