// <auto-generated/>
#nullable enable
namespace GoGit.Interop;

public sealed class CheckoutOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public CheckoutOptions()
    {
        NativeMethods.GitCheckoutOptionsNew(out _handle);
    }

    public CheckoutOptions SetHash(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCheckoutOptionsSetHash(_handle, value));
        return this;
    }

    public CheckoutOptions SetBranch(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCheckoutOptionsSetBranch(_handle, value));
        return this;
    }

    public CheckoutOptions SetCreate(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCheckoutOptionsSetCreate(_handle, value ? 1 : 0));
        return this;
    }

    public CheckoutOptions SetForce(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCheckoutOptionsSetForce(_handle, value ? 1 : 0));
        return this;
    }

    public CheckoutOptions SetKeep(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCheckoutOptionsSetKeep(_handle, value ? 1 : 0));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitCheckoutOptionsFree(_handle);
        _handle = 0;
    }
}
