// <auto-generated/>
#nullable enable
namespace GoGit.Interop;

public sealed class CleanOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public CleanOptions()
    {
        NativeMethods.GitCleanOptionsNew(out _handle);
    }

    public CleanOptions SetDir(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitCleanOptionsSetDir(_handle, value ? 1 : 0));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitCleanOptionsFree(_handle);
        _handle = 0;
    }
}
