// <auto-generated/>
#nullable enable
namespace GoGit.Interop;

public sealed class ResetOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public ResetOptions()
    {
        NativeMethods.GitResetOptionsNew(out _handle);
    }

    public ResetOptions SetCommit(string value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitResetOptionsSetCommit(_handle, value));
        return this;
    }

    public ResetOptions SetMode(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitResetOptionsSetMode(_handle, value));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitResetOptionsFree(_handle);
        _handle = 0;
    }
}
