// <auto-generated/>
#nullable enable
namespace GoGit.Interop;

public sealed class SubmoduleUpdateOptions : IDisposable
{
    private long _handle;
    private bool _disposed;

    internal long Handle => _handle;

    public SubmoduleUpdateOptions()
    {
        NativeMethods.GitSubmoduleUpdateOptionsNew(out _handle);
    }

    public SubmoduleUpdateOptions SetInit(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleUpdateOptionsSetInit(_handle, value ? 1 : 0));
        return this;
    }

    public SubmoduleUpdateOptions SetNoFetch(bool value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleUpdateOptionsSetNoFetch(_handle, value ? 1 : 0));
        return this;
    }

    public SubmoduleUpdateOptions SetAuth(Auth value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleUpdateOptionsSetAuth(_handle, value.Handle));
        return this;
    }

    public SubmoduleUpdateOptions SetDepth(int value)
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
        NativeMethods.ThrowIfError(NativeMethods.GitSubmoduleUpdateOptionsSetDepth(_handle, value));
        return this;
    }

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        NativeMethods.GitSubmoduleUpdateOptionsFree(_handle);
        _handle = 0;
    }
}
