// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json.Serialization;

namespace GoGit.Interop;

public sealed class BlameResult
{
    [JsonPropertyName("path")]
    public string Path { get; init; } = "";

    [JsonPropertyName("rev")]
    public string Rev { get; init; } = "";

    [JsonPropertyName("lines")]
    public BlameLine[] Lines { get; init; } = [];
}

public sealed class BlameLine
{
    [JsonPropertyName("author")]
    public string Author { get; init; } = "";

    [JsonPropertyName("authorEmail")]
    public string AuthorEmail { get; init; } = "";

    [JsonPropertyName("hash")]
    public string Hash { get; init; } = "";

    [JsonPropertyName("date")]
    public long Date { get; init; }

    [JsonPropertyName("text")]
    public string Text { get; init; } = "";

    public DateTimeOffset DateTimeOffset => DateTimeOffset.FromUnixTimeSeconds(Date);
}
