// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json.Serialization;

namespace GoGit.Interop;

public sealed class BranchConfig
{
    [JsonPropertyName("name")]
    public string Name { get; init; } = "";

    [JsonPropertyName("remote")]
    public string Remote { get; init; } = "";

    [JsonPropertyName("merge")]
    public string Merge { get; init; } = "";

    [JsonPropertyName("rebase")]
    public string Rebase { get; init; } = "";

    [JsonPropertyName("description")]
    public string? Description { get; init; }
}
