// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json.Serialization;

namespace GoGit.Interop;

public sealed class FileStat
{
    [JsonPropertyName("name")]
    public string Name { get; init; } = "";

    [JsonPropertyName("addition")]
    public int Addition { get; init; }

    [JsonPropertyName("deletion")]
    public int Deletion { get; init; }
}
