// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json.Serialization;

namespace GoGit.Interop;

public sealed class RemoteConfig
{
    [JsonPropertyName("name")]
    public string Name { get; init; } = "";

    [JsonPropertyName("urls")]
    public string[] URLs { get; init; } = [];

    [JsonPropertyName("fetch")]
    public string[] Fetch { get; init; } = [];
}
