// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json.Serialization;

namespace GoGit.Interop;

public sealed class SubmoduleConfig
{
    [JsonPropertyName("name")]
    public string Name { get; init; } = "";

    [JsonPropertyName("path")]
    public string Path { get; init; } = "";

    [JsonPropertyName("url")]
    public string URL { get; init; } = "";

    [JsonPropertyName("branch")]
    public string Branch { get; init; } = "";
}
