// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json.Serialization;

namespace GoGit.Interop;

public sealed class SubmoduleStatusInfo
{
    [JsonPropertyName("path")]
    public string Path { get; init; } = "";

    [JsonPropertyName("current")]
    public string Current { get; init; } = "";

    [JsonPropertyName("expected")]
    public string Expected { get; init; } = "";

    [JsonPropertyName("branch")]
    public string Branch { get; init; } = "";
}
