// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json.Serialization;

namespace GoGit.Interop;

public sealed class TreeEntryInfo
{
    [JsonPropertyName("name")]
    public string Name { get; init; } = "";

    [JsonPropertyName("hash")]
    public string Hash { get; init; } = "";

    [JsonPropertyName("mode")]
    public uint Mode { get; init; }
}
