// Code generated by gogit-interop/generate. DO NOT EDIT.

namespace GoGit.Interop;

/// <summary>
/// The git file mode (type and permission bits) for a tree entry.
/// Values correspond to the standard git object mode octal constants.
/// </summary>
public enum TreeEntryMode : uint
{
    /// <summary>No object / non-existent entry.</summary>
    Nonexistent = 0,

    /// <summary>A directory (tree object). Octal <c>040000</c>.</summary>
    Directory = 0x4000,

    /// <summary>A regular non-executable file. Octal <c>100644</c>.</summary>
    NonExecutableFile = 0x81A4,

    /// <summary>A regular non-executable group-writable file. Octal <c>100664</c>.</summary>
    NonExecutableGroupWritableFile = 0x81B4,

    /// <summary>A regular executable file. Octal <c>100755</c>.</summary>
    ExecutableFile = 0x81ED,

    /// <summary>A symbolic link. Octal <c>120000</c>.</summary>
    SymbolicLink = 0xA000,

    /// <summary>A git link (submodule). Octal <c>160000</c>.</summary>
    GitLink = 0xE000,
}
