// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json.Serialization;

namespace GoGitDotNet;

/// <summary>A single file change within a tree diff, as returned by <see cref="Tree.Diff"/>.</summary>
public sealed class DiffChange
{
    [JsonPropertyName("action")]
    public string Action { get; init; } = "";

    [JsonPropertyName("fromPath")]
    public string? FromPath { get; init; }

    [JsonPropertyName("toPath")]
    public string? ToPath { get; init; }

    [JsonPropertyName("fromHash")]
    public string? FromHash { get; init; }

    [JsonPropertyName("toHash")]
    public string? ToHash { get; init; }
}
