// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json.Serialization;

namespace GoGitDotNet;

/// <summary>Per-file line addition/deletion statistics for a commit, as returned by <see cref="Commit.Stats"/>.</summary>
public sealed class FileStat
{
    [JsonPropertyName("name")]
    public string Name { get; init; } = "";

    [JsonPropertyName("addition")]
    public int Addition { get; init; }

    [JsonPropertyName("deletion")]
    public int Deletion { get; init; }
}
