// Code generated by gogit-interop/generate. DO NOT EDIT.
#nullable enable
using System.Text.Json.Serialization;

namespace GoGitDotNet;

/// <summary>A git reference (branch, tag, or other ref) as advertised by a remote or stored in a repository.</summary>
public sealed class ReferenceInfo
{
    /// <summary>The full reference name, e.g. <c>refs/heads/main</c>.</summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>The SHA-1 hash the reference points to.</summary>
    [JsonPropertyName("hash")]
    public required string Hash { get; init; }
}
