// <auto-generated/>
#nullable enable
namespace GoGit.Interop;

public sealed class Commit
{
    public required string Hash { get; init; }
    public required string Message { get; init; }
    public required string AuthorName { get; init; }
    public required string AuthorEmail { get; init; }
    public required DateTimeOffset AuthorTimestamp { get; init; }
}
