// <auto-generated/>
#nullable enable
using System.Text.Json.Serialization;

namespace GoGit.Interop;

public sealed class ReferenceInfo
{
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("hash")]
    public required string Hash { get; init; }
}
